export const language = {
	en: {
		activate: `Activate`,
		add: `Add`,
		addBlock: `Add a block`,
		addCaption: `Add a caption`,
		addCategory: `Add a category`,
		addCredits: `Add Credits`,
		addFunds: `Add Funds`,
		addLink: `Add a link`,
		address: `Address`,
		addSection: `Add Section`,
		addTheme: `Add a theme`,
		addTo: `Add To `,
		addTopic: `Add a tag`,
		addUser: `Add a user`,
		alignCaption: `Align caption`,
		all: `All`,
		amount: `Amount`,
		amountToShare: `Amount to Share`,
		app: `Portal`,
		appearance: `Appearance`,
		approve: `Approve`,
		approved: `Approved`,
		arioToken: `AR.IO Token`,
		arnsBuyDescription: `Register permanently`,
		arnsDashesValidation: `No Leading or Trailing Dashes`,
		arnsLeaseDescription: `Register for 1-5 years`,
		arnsMaxCharsValidation: `Max: 51 Characters`,
		arnsNameValidation: `Cannot be WWW`,
		arnsSpecialCharsValidation: `No Special Characters`,
		article: `Article`,
		assignedElsewhere: `Assigned Elsewhere`,
		assignedElsewhereInfo: `These domains point to other sites.`,
		assignedToThisPortal: `Assigned to This Portal`,
		assignedToThisPortalInfo: `These domains currently point to this portal.`,
		assigning: `Assigning…`,
		assignmentRemoved: `Assignment removed`,
		assignToThisPortal: `Assign to This Portal`,
		author: `Author`,
		available: `Available`,
		background: `Background`,
		bio: `Bio`,
		blocks: `Blocks`,
		blocksEmpty: `Press enter, click here, or choose a block type`,
		bodyText: `Body Text`,
		bottom: `Bottom`,
		buy: `Buy`,
		calculating: `Calculating`,
		cancel: `Cancel`,
		caption: `Caption`,
		categories: `Categories`,
		categoriesUpdated: `Categories Updated`,
		categoryAdded: `Category Added`,
		categoryDeleteConfirmation: `Yes, remove categories`,
		categoryDeleteConfirmationInfo: `Are you sure you want to want to remove the following categories?`,
		categoryDuplicateError: `Duplicate category names found`,
		checkoutCurrentBalance: `Current Balance:`,
		checkoutDomainName: `Domain Name:`,
		checkoutFinalBalance: `Final Balance:`,
		checkoutRegistrationPeriod: `Registration Period:`,
		checkoutTotalDue: `Total Due:`,
		chooseAppearance: `Choose Appearance`,
		choosePayment: `Choose Payment`,
		clear: `Clear`,
		close: `Close`,
		closeToolkit: `Close Toolkit`,
		colorPicker: `Color Picker`,
		colors: `Colors`,
		colorScheme: `Color Scheme`,
		confirm: `Confirm`,
		confirmDeletion: `Confirm Deletion`,
		confirmDomainAssignment: `Confirm Domain Assignment`,
		confirmDomainAssignmentMessage: `Are you sure you want to assign this domain to this portal? This will redirect the domain to point to your current portal.`,
		confirmRegistration: `Confirm Registration`,
		connect: `Connect`,
		connectToContinue: `Connect Your Wallet to Continue`,
		connectWallet: `Connect Your Wallet`,
		continue: `Continue`,
		contribute: `Contribute`,
		controlled: `Controlled`,
		conversion: `Conversion`,
		convertToLink: `Convert to Link`,
		copied: `Copied`,
		copyProfileAddress: `Copy Profile Address`,
		costToUpload: `Cost to Upload`,
		create: `Create`,
		created: `Created`,
		createPage: `Create a Page`,
		createPageInfo: `Create an Info Page`,
		createPortal: `Create a New Portal`,
		createPost: `Create a Post`,
		createProfile: `Create Your Profile`,
		creditBalance: `Credit Balance`,
		credits: `Credits`,
		creditsSharedSuccessfully: `Credits Shared Successfully`,
		current: `Current`,
		currentBalanceLabel: `Current Balance:`,
		custom: `Custom`,
		customAmount: `Custom Amount`,
		customAmountTurboInfo: `min $5 - max $10,000`,
		date: `Date`,
		ddPlaceholder: `DD`,
		delete: `Delete`,
		deleteBlock: `Delete Block`,
		deleteCaption: `Delete Caption`,
		deleteSection: `Delete Section`,
		description: `Description`,
		descriptionUpdated: `Description Updated`,
		design: `Design`,
		designLink: `Go to Full Designer`,
		detailId: `ID`,
		detailRegistered: `Registered`,
		detailTarget: `Target`,
		detailType: `Type`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		docs: `Docs`,
		domainAvailable: `This domain is available`,
		domainName: `Domain Name`,
		domainNameLabel: `Domain Name:`,
		domainRegistration: `Domain Registration`,
		domainRegistrationStep1: `Step 1: Find a name`,
		domainRegistrationStep2: `Step 2: Registration Period`,
		domainRegistrationStep3: `Step 3: Checkout`,
		domainRegistrationSuccessful: `Domain Registration Successful!`,
		domains: `Domains`,
		domainsLink: `Go to Domains`,
		domainsUpdated: `Domains Updated`,
		domainUnavailable: `This domain is not available`,
		done: `Done`,
		draft: `Draft`,
		dynamicElements: `Dynamic Elements`,
		edit: `Edit`,
		editCaption: `Edit Caption`,
		editDescription: `Edit Description`,
		editHtml: `Edit HTML`,
		editLink: `Edit Link`,
		editPortal: `Edit Portal`,
		editPostTopics: `Edit Post Tags`,
		editProfile: `Edit Your Profile`,
		editReleaseDate: `Edit Release Date`,
		editSiteCategories: `Edit Site Categories`,
		editSocialLinks: `Edit Social Links`,
		editThemeName: `Edit Theme Name`,
		effectiveBalance: `Effective Balance`,
		emojiSearch: `Search emojis...`,
		errorExtendingLease: `Error extending lease.`,
		errorOccurred: `Error Occurred`,
		errorRevokingCredits: `Error Revoking Credits`,
		errorSharingCredits: `Error Sharing Credits`,
		errorUpdatingPortal: `Error Updating Portal`,
		errorUpdatingPost: `Error Updating Post`,
		errorUpdatingProfile: `Error Updating Profile`,
		errorUpgradingRecord: `Error upgrading record.`,
		errorUploadingThumbnail: `Error Uploading Thumbnail`,
		failedToFetchBalance: `Failed to fetch balance`,
		featuredImage: `Featured Image`,
		fetching: `Fetching`,
		fetchingPortals: `Fetching Portals`,
		fetchingPrices: `Fetching Prices`,
		fetchingYourDomains: `Fetching your domains`,
		filter: `Filter`,
		filterBy: `Filter By`,
		fonts: `Fonts`,
		fontsUpdated: `Fonts Updated`,
		fromLibrary: `Choose From Library`,
		fund: `Fund`,
		fundTurboBalance: `Fund Turbo Balance`,
		fundTurboBalanceInfoDetail: `Credits will be automatically added to your Turbo balance, and you can start using them right away.`,
		fundTurboBalanceInfoHeader: `Buy Credits`,
		fundTurboPaymentDetail: `Payments are powered by ArDrive Turbo, and handled securely by Stripe.`,
		fundTurboPaymentHeader: `Complete Payment`,
		getTestnetTokens: `Get Testnet Tokens`,
		gettingCategories: `Getting Categories`,
		gettingDomains: `Getting Domains`,
		gettingInfo: `Getting Your Info`,
		gettingLinks: `Getting Links`,
		gettingPages: `Getting Pages`,
		gettingPosts: `Getting Posts`,
		gettingProfile: `Getting Your Profile`,
		gettingThemes: `Getting Themes`,
		gettingTopics: `Getting Tags`,
		gettingUploads: `Getting Uploads`,
		gettingUsers: `Getting Users`,
		getTokens: `Get Tokens`,
		givenApprovals: `Given Approvals`,
		goBack: `Go Back`,
		goToDomain: `Go To Domain`,
		goToPayment: `Go to Payment`,
		goToSite: `Go to Site`,
		handle: `Handle`,
		headers: `Headers`,
		help: `Help`,
		helpCenter: `Help Center`,
		hhPlaceholder: `HH`,
		hideTools: `Hide Tools`,
		hideYourRecords: `Hide Your Records`,
		home: `Home`,
		htmlEditor: `HTML Editor`,
		icon: `Icon`,
		iconDeleteConfirmation: `Yes, Remove Icon`,
		iconDeleteConfirmationInfo: `Are you sure you want to want to remove your site icon?`,
		iconUpdated: `Icon Updated`,
		image: `Image`,
		images: `Images`,
		immediately: `Immediately`,
		inactiveComments: `Inactive Comments`,
		infoPages: `Info Pages`,
		insertFromUrl: `Insert From URL`,
		insufficientBalance: `Insufficient Balance. Add credits to continue.`,
		insufficientBalanceMessage: `Insufficient Balance. Add credits to continue.`,
		insufficientTarioBalance: `Insufficient tario balance. Get testnet tokens to continue.`,
		invitePending: `Invite Pending`,
		invites: `Invites`,
		invitesInfo: `The following portal(s) have invited you to join them ! Click on the portal you’d like to join to get started.`,
		language: `Language`,
		larger: `Larger`,
		layout: `Layout`,
		layoutUpdated: `Layout Updated`,
		learn: `Learn`,
		lease: `Lease`,
		leaseExtendedSuccessfully: `Lease extended successfully.`,
		left: `Left`,
		link: `Link`,
		linkAdded: `Link Added`,
		linkDeleteConfirmation: `Yes, Remove Links`,
		linkDeleteConfirmationInfo: `Are you sure you want to want to remove the following links?`,
		linksUpdated: `Links Updated`,
		loading: `Loading`,
		loadingDataFor: `Loading Data For:`,
		loadingPage: `Loading Page`,
		loadingPortal: `Loading Your Portal`,
		loadingPost: `Loading Post`,
		loggingIn: `Logging In`,
		logo: `Logo`,
		logoAlt: `Logo`,
		logoDeleteConfirmation: `Yes, Remove Logo`,
		logoDeleteConfirmationInfo: `Are you sure you want to want to remove your site logo?`,
		logoUpdated: `Logo Updated`,
		manage: `Manage`,
		manageUser: `Manage User`,
		max: `Max`,
		maxCharsReached: `Max Chars Reached`,
		media: `Media`,
		mediaDeleteConfirmation: `Yes, Remove Media`,
		mediaDeleteConfirmationInfo: `Are you sure you want to want to remove this media?`,
		mediaLibrary: `Media Library`,
		mediaUpdated: `Media Updated`,
		mediaUploadCostInfo: `Credits from your upload balance will be used for this upload.`,
		mediaUploaded: `Media Uploaded`,
		mediaUploadInfo: `Insert media from a URL, upload new media, or choose from your library.`,
		missingPostFields: `Some required fields are missing from this post.`,
		mmPlaceholder: `MM`,
		moderation: `Moderation`,
		month: `Month`,
		more: `More`,
		moreActions: `More Actions`,
		mostRead: `Most Read`,
		myComments: `My Comments`,
		myPosts: `My Posts`,
		myProfile: `My Profile`,
		myWallet: `My Wallet`,
		name: `Name`,
		next: `Next`,
		noCategoriesFound: `No Categories Found`,
		noDomainsFound: `No Domains Found`,
		noDomainsFoundInfo: `Domains are shown here when they exist on this network's ArNS and are owned by your wallet.`,
		noExternalPortals: `No External Portals to Contribute To`,
		noInactiveCommentsFound: `No inactive comments found`,
		noInvites: `No Invites`,
		noInvitesInfo: `Currently there are no portal invites found for your wallet address or profile.`,
		noInvitesProfileInfo: `You must connect your wallet and create a profile in order to accept invites.`,
		noLinksFound: `No Links Found`,
		none: `None`,
		noPagesFound: `No Pages Found`,
		noPortalsFound: `No Portals Found`,
		noPostsFound: `No Posts Found`,
		noProfileFound: `No Associated Profile Found`,
		noRequestsFound: `No Requests Found`,
		noThemesFound: `No Themes Found`,
		noTopicsFound: `No Tags Found`,
		noUploadsFound: `No Uploads Found`,
		noUsersFound: `No Users Found`,
		page: `Page`,
		pageNotFound: `Page Not Found`,
		pages: `Pages`,
		pageSaved: `Page Saved`,
		pageTitle: `Page Title`,
		pending: `Pending`,
		permanent: `Permanent`,
		permissionBaseDenied: `You do not have permission to access this portal`,
		permissionExternalContributor: `You are an external contributor on this portal. You will see this portal as an option to contribute to from your other portals.`,
		permissions: `Permissions`,
		pleaseReviewAndConfirm: `Please review and confirm`,
		portalCreate: `Create a New Portal`,
		portalCreated: `Portal Created`,
		portalCreatingInfo: `Creating Your Portal`,
		portalHeader: `Your Portal`,
		portalIconAlt: `Portal Icon`,
		portalReturn: `Return to Portal Home`,
		portals: `Portal`,
		portalsHeader: `Connect to Portal`,
		portalsInfo: `Your portals will be listed here`,
		portalsReturn: `Exit to All Portals`,
		portalsSubheader: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor, Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
		portalUpdated: `Portal Updated`,
		portalUpdatingInfo: `Updating Your Portal`,
		post: `Post`,
		postApproved: `Post Approved`,
		postCreateDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo`,
		postCreateHeader: `Create a Post`,
		postCreateSubheader: `Post Options`,
		posts: `Posts`,
		postSaved: `Post Saved`,
		postsLink: `Go to All Posts`,
		postStatusUpdated: `Post Status Updated`,
		postTitle: `Post Title`,
		postTopics: `Post Tags`,
		postUpdated: `Post Updated`,
		prefill: `Prefill`,
		previous: `Previous`,
		primaryDomain: `Primary Domain`,
		profile: `Profile`,
		profileCreated: `Profile Created`,
		profileCreatingInfo: `Creating Your Profile`,
		profileMenu: `Profile Menu`,
		profileUpdated: `Profile Updated`,
		profileUpdatingInfo: `Updating Your Profile`,
		publication: `Publication`,
		published: `Published`,
		publishTheme: `Publish Theme`,
		receivedApprovals: `Received Approvals`,
		recentPosts: `Recent Posts`,
		recommended: `Recommended`,
		redirectFailed: `Failed to redirect domain:`,
		redirectSuccess: `Domain successfully redirected to portal!`,
		registerDomain: `Register Domain`,
		registerErrorHeader: `Registration Failed`,
		registerErrorRetry: `Try Again`,
		registeringProgress: `Registering...`,
		registerStepCheckout: `Step 3: Checkout`,
		registerStepFindName: `Step 1: Find a name`,
		registerStepPeriod: `Step 2: Registration Period`,
		registerSuccessAnother: `Register Another Domain`,
		registerSuccessDomain: `Domain:`,
		registerSuccessHeader: `Domain Registration Successful!`,
		registerSuccessTx: `Transaction ID:`,
		registerSuccessType: `Type:`,
		registrationFailed: `Registration Failed`,
		registrationPeriod: `Registration Period:`,
		registrationPeriodLabel: `Registration Period:`,
		reject: `Reject`,
		release: `Release`,
		releaseDate: `Release Date`,
		releaseDateUpdated: `Release Date Updated`,
		remaining: `Remaining`,
		remainingAfterUpload: `Remaining After Upload`,
		remove: `Remove`,
		removeAssignmentConfirm: `Remove Domain Assignment`,
		removeAssignmentConfirmMessage: `Are you sure you want to remove this domain from the current portal?`,
		removeAvatar: `Remove Avatar`,
		removeBanner: `Remove Banner`,
		removeCaption: `Remove Caption`,
		removeFromPortal: `Unassign from Portal`,
		removeIcon: `Remove Icon`,
		removeLogo: `Remove Logo`,
		removeWallpaper: `Remove Wallpaper`,
		removingMedia: `Removing Media`,
		requests: `Requests`,
		resolving: `Resolving`,
		returnHome: `Return Home`,
		review: `Review`,
		reviewPost: `Review Post`,
		reviewPostDetails: `Review Post Details`,
		revoke: `Revoke`,
		right: `Right`,
		role: `Role`,
		roleDescriptionAdmin: [
			'Update Setup & Design',
			'Add & Remove Media',
			'Add & Remove Users',
			'Add & Remove Posts',
			'Approve Contributor Posts',
			'Remove Post Comments',
			'Register Domains',
		],
		roleDescriptionContributor: ['Add Post Requests'],
		roleDescriptionExternalContributor: ['Add Post Requests from another Portal'],
		roleDescriptionModerator: ['Approve Contributor Posts', 'Remove Post Comments'],
		save: `Save`,
		saving: `Saving`,
		seeLess: `See less`,
		seeMore: `See more`,
		select: `Select`,
		selectParentCategory: `Select Parent Category`,
		selectPortal: `Select Your Portal`,
		setPrimaryDomain: `Set as Primary Domain`,
		settings: `Settings`,
		setup: `Setup`,
		setupLink: `Go to Full Setup`,
		shareCredits: `Share Credits`,
		showCaptionTools: `Show Caption Tools`,
		showDomainActions: `Show Domain Actions`,
		showingRange: (start: number, end: number, total: number) => `Showing ${start} - ${end} of ${total}`,
		showYourRecords: `Show Your Records`,
		sidebarClose: `Close Sidebar`,
		sidebarOpen: `Open Sidebar`,
		siteCategories: `Site Categories`,
		siteIconInfo: `Site Icon (Favicon) - Standard: 32 × 32`,
		smaller: `Smaller`,
		socialLinks: `Social Links`,
		sortBy: `Sort By`,
		sortNewestToOldest: `Newest to Oldest`,
		sortOldestToNewest: `Oldest to Newest`,
		status: `Status`,
		submit: `Submit`,
		successfullyFunded: `Successfully Funded`,
		successfullyRevokedCredits: `Successfully Revoked Credits`,
		testnetMode: `This is testnet mode. You can get tario tokens from the testnet faucet.`,
		testnetModeMsg1: `This is testnet mode. You can get tario tokens from the testnet faucet.`,
		testnetModeMsg2: `Visit the https://faucet.arweave.net/ faucet to get tokens for testing.`,
		text: `Text`,
		themeDeleteConfirmation: `Yes, Remove Theme`,
		themeDeleteConfirmationInfo: `Are you sure you want to remove the following theme?`,
		themes: `Themes`,
		themesUpdated: `Themes Updated`,
		thumbnailUpdated: `Thumbnail Updated`,
		time: `Time`,
		toolkit: `Toolkit`,
		top: `Top`,
		topicAdded: `Tag Added`,
		topicDeleteConfirmation: `Yes, Remove Tags`,
		topicDeleteConfirmationInfo: `Are you sure you want to want to remove the following tags?`,
		topics: `Tags`,
		topicsUpdated: `Tags Updated`,
		totalDueLabel: `Total Due:`,
		toThisPortal: `To This Portal`,
		transactionId: `Transaction ID`,
		unassigned: `Unassigned`,
		unassignedAnt: `Unassigned ANT`,
		unassignedInfo: `No explicit target set. Assign to route to this portal.`,
		unauthorized: `Unauthorized`,
		unauthorizedDomainManage: `Only portal admins can manage domains.`,
		unauthorizedDomainRegister: `Only portal admins can register domain names.`,
		unauthorizedPortalUpdate: `Only portal admins can modify site setup.`,
		unauthorizedPortalUpdateMedia: `Only portal admins can add or remove media.`,
		unauthorizedPostCreate: `Only portal admins or contributors can create new posts.`,
		unauthorizedPostReview: `Only portal admins or moderators can review posts.`,
		unauthorizedUsersUpdate: `Only portal admins can add or modify users.`,
		untitledPost: `Untitled Post`,
		updateAvailable: `Update Available`,
		updating: `Updating`,
		updatingFonts: `Updating Fonts`,
		updatingLayout: `Updating Layout`,
		updatingPortal: `Updating Portal`,
		updatingPostStatus: `Updating Post Status`,
		updatingTheme: `Updating Theme`,
		upgradeDomain: `Upgrade Domain`,
		upgradeToPermanentSuccessfully: `Upgraded to permanent successfully.`,
		upload: `Upload`,
		uploadAvatar: `Upload Avatar`,
		uploadBanner: `Upload Banner`,
		uploadCancelled: `Upload Cancelled`,
		uploadFeaturedImage: `Upload Featured Image`,
		uploadIcon: `Upload Icon`,
		uploadingMedia: `Uploading Media`,
		uploadLogo: `Upload Logo`,
		uploads: `Uploads`,
		uploadWallpaper: `Upload Wallpaper`,
		url: `URL`,
		urlPlaceholder: `https://`,
		usd: `USD`,
		user: 'User',
		userAdded: `User Added`,
		userInviteInfo: `The user being added will see this invite in their Portal Home Screen.`,
		users: `Users`,
		usersLink: `Go to Users`,
		userUpdated: `User Updated`,
		validating: `validating…`,
		validationFailed: `Validation Failed`,
		validationFailedInfo: `These domains couldn't be validated. They appear as unassigned until manually refreshed.`,
		validationFailedStatus: `Validation failed - refresh to retry`,
		video: `Video`,
		videos: `Videos`,
		view: `View`,
		viewInfo: `View Info`,
		viewProfile: `View Profile`,
		visitFaucet: `Visit Faucet.`,
		waitingForProfile: `Waiting for Your Profile`,
		wallet: `Wallet`,
		walletAddress: `Wallet Address`,
		walletOrPortalUnavailable: `Wallet not connected or portal not available`,
		wallpaper: `Wallpaper`,
		wallpaperDeleteConfirmation: `Yes, Remove Wallpaper`,
		wallpaperDeleteConfirmationInfo: `Are you sure you want to want to remove your site wallpaper?`,
		wallpaperUpdated: `Wallpaper Updated`,
		welcome: `Welcome`,
		year: `Year`,
		years: `Years`,
		youAreInvited: `You're Invited`,
		yourRecords: `Your Records`,
		yourUploadBalance: `Your Upload Balance`,
		yyyyPlaceholder: `YYYY`,
	},
	es: {
		// === UNTRANSLATED START ===
		// TODO: translate

		addBlock: `Add a block`,
		addSection: `Add Section`,
		createPageInfo: `Create an Info Page`,
		custom: `Custom`,
		deleteSection: `Delete Section`,
		dynamicElements: `Dynamic Elements`,
		editHtml: `Edit HTML`,
		htmlEditor: `HTML Editor`,
		infoPages: `Info Pages`,
		loadingPage: `Loading Page`,
		pageSaved: `Page Saved`,
		publication: `Publication`,
		upgradeDomain: `Upgrade Domain`,
		yourRecords: `Your Records`,
		// === UNTRANSLATED END ===
		activate: `Activar`,
		add: `Agregar`,
		addCaption: `Agregar descripción`,
		addCategory: `Agregar categoría`,
		addCredits: `Agregar créditos`,
		addFunds: `Agregar fondos`,
		addLink: `Agregar enlace`,
		address: `Dirección`,
		addTheme: `Agregar tema`,
		addTo: `Agregar a `,
		addTopic: `Agregar etiqueta`,
		addUser: `Agregar usuario`,
		alignCaption: `Alinear descripción`,
		all: `Todos`,
		amount: `Cantidad`,
		amountToShare: `Cantidad a compartir`,
		app: `Portal`,
		appearance: `Apariencia`,
		approve: `Aprobar`,
		approved: `Aprobado`,
		arioToken: `Token AR.IO`,
		arnsBuyDescription: `Registrar permanentemente`,
		arnsDashesValidation: `Sin guiones al inicio o al final`,
		arnsLeaseDescription: `Registrar por 1-5 años`,
		arnsMaxCharsValidation: `Máximo: 51 caracteres`,
		arnsNameValidation: `No puede ser WWW`,
		arnsSpecialCharsValidation: `Sin caracteres especiales`,
		article: `Artículo`,
		assignedElsewhere: `Asignados en otro lugar`,
		assignedElsewhereInfo: `Estos dominios apuntan a otros sitios.`,
		assignedToThisPortal: `Asignados a este portal`,
		assignedToThisPortalInfo: `Estos dominios apuntan a este portal.`,
		assigning: `Asignando…`,
		assignmentRemoved: `Asignación eliminada`,
		assignToThisPortal: `Asignar a este portal`,
		author: `Autor`,
		available: `Disponible`,
		background: `Fondo`,
		bio: `Biografía`,
		blocks: `Bloques`,
		blocksEmpty: `Comienza tu publicación - Presiona enter, haz clic aquí o elige un tipo de bloque`,
		bodyText: `Texto principal`,
		bottom: `Inferior`,
		buy: `Comprar`,
		calculating: `Calculando`,
		cancel: `Cancelar`,
		caption: `Descripción`,
		categories: `Categorías`,
		categoriesUpdated: `Categorías actualizadas`,
		categoryAdded: `Categoría agregada`,
		categoryDeleteConfirmation: `Sí, eliminar categorías`,
		categoryDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar las siguientes categorías?`,
		categoryDuplicateError: `Se encontraron nombres de categoría duplicados`,
		checkoutCurrentBalance: `Saldo actual:`,
		checkoutDomainName: `Nombre de dominio:`,
		checkoutFinalBalance: `Saldo final:`,
		checkoutRegistrationPeriod: `Período de registro:`,
		checkoutTotalDue: `Total a pagar:`,
		chooseAppearance: `Elegir apariencia`,
		choosePayment: `Elegir pago`,
		clear: `Limpiar`,
		close: `Cerrar`,
		closeToolkit: `Cerrar kit de herramientas`,
		colorPicker: `Selector de color`,
		colors: `Colores`,
		colorScheme: `Esquema de color`,
		confirm: `Confirmar`,
		confirmDeletion: `Confirmar eliminación`,
		confirmDomainAssignment: `Confirmar asignación de dominio`,
		confirmDomainAssignmentMessage: `¿Estás seguro de que deseas asignar este dominio a este portal? Esto redirigirá el dominio para que apunte a tu portal actual.`,
		confirmRegistration: `Confirmar registro`,
		connect: `Conectar`,
		connectToContinue: `Conecta tu billetera para continuar`,
		connectWallet: `Conectar tu billetera`,
		continue: `Continuar`,
		contribute: `Contribuir`,
		controlled: `Controlado`,
		conversion: `Conversión`,
		convertToLink: `Convertir en enlace`,
		copied: `Copiado`,
		copyProfileAddress: `Copiar dirección de perfil`,
		costToUpload: `Costo para subir`,
		create: `Crear`,
		created: `Creado`,
		createPage: `Crear una página`,
		createPortal: `Crear un nuevo portal`,
		createPost: `Crear una publicación`,
		createProfile: `Crear tu perfil`,
		creditBalance: `Saldo de subida`,
		credits: `Créditos`,
		creditsSharedSuccessfully: `Créditos compartidos exitosamente`,
		current: `Actual`,
		currentBalanceLabel: `Saldo actual:`,
		customAmount: `Cantidad personalizada`,
		customAmountTurboInfo: `mín $5 - máx $10,000`,
		date: `Fecha`,
		ddPlaceholder: `DD`,
		delete: `Eliminar`,
		deleteBlock: `Eliminar bloque`,
		deleteCaption: `Eliminar descripción`,
		description: `Descripción`,
		descriptionUpdated: `Descripción actualizada`,
		design: `Diseño`,
		designLink: `Ir al diseñador completo`,
		detailId: `ID`,
		detailRegistered: `Registrado`,
		detailTarget: `Destino`,
		detailType: `Tipo`,
		disconnect: `Desconectar`,
		dismiss: `Descartar`,
		docs: `Documentos`,
		domainAvailable: `Este dominio está disponible`,
		domainName: `Nombre de dominio`,
		domainNameLabel: `Nombre de dominio:`,
		domainRegistration: `Registro de dominio`,
		domainRegistrationStep1: `Paso 1: Encuentra un nombre`,
		domainRegistrationStep2: `Paso 2: Período de registro`,
		domainRegistrationStep3: `Paso 3: Checkout`,
		domainRegistrationSuccessful: `¡Registro de dominio exitoso!`,
		domains: `Dominios`,
		domainsLink: `Ir a dominios`,
		domainsUpdated: `Dominios actualizados`,
		domainUnavailable: `Este dominio no está disponible`,
		done: `Listo`,
		draft: `Borrador`,
		edit: `Editar`,
		editCaption: `Editar descripción`,
		editDescription: `Editar descripción`,
		editLink: `Editar enlace`,
		editPortal: `Editar portal`,
		editPostTopics: `Editar etiquetas de publicación`,
		editProfile: `Editar tu perfil`,
		editReleaseDate: `Editar fecha de lanzamiento`,
		editSiteCategories: `Editar categorías del sitio`,
		editSocialLinks: `Editar enlaces sociales`,
		editThemeName: `Editar nombre del tema`,
		effectiveBalance: `Saldo efectivo`,
		emojiSearch: `Buscar emojis...`,
		errorExtendingLease: `Error extendiendo arrendamiento.`,
		errorOccurred: `Ocurrió un error`,
		errorRevokingCredits: `Error revocando créditos`,
		errorSharingCredits: `Error compartiendo créditos`,
		errorUpdatingPortal: `Error al actualizar el portal`,
		errorUpdatingPost: `Error al actualizar la publicación`,
		errorUpdatingProfile: `Error al actualizar el perfil`,
		errorUpgradingRecord: `Error actualizando registro.`,
		errorUploadingThumbnail: `Error al subir la miniatura`,
		failedToFetchBalance: `Error al obtener el saldo`,
		featuredImage: `Imagen destacada`,
		fetching: `Obteniendo`,
		fetchingPortals: `Obteniendo portales`,
		fetchingPrices: `Obteniendo precios`,
		fetchingYourDomains: `Obteniendo tus dominios`,
		filter: `Filtrar`,
		filterBy: `Filtrar por`,
		fonts: `Fuentes`,
		fontsUpdated: `Fuentes actualizadas`,
		fromLibrary: `Elegir de la biblioteca`,
		fund: `Fondear`,
		fundTurboBalance: `Fondear saldo Turbo`,
		fundTurboBalanceInfoDetail: `Los créditos se agregarán automáticamente a tu saldo Turbo y podrás usarlos de inmediato.`,
		fundTurboBalanceInfoHeader: `Comprar créditos`,
		fundTurboPaymentDetail: `Los pagos son potenciados por ArDrive Turbo y manejados de forma segura por Stripe.`,
		fundTurboPaymentHeader: `Completar pago`,
		getTestnetTokens: `Obtener tokens de testnet`,
		gettingCategories: `Obteniendo categorías`,
		gettingDomains: `Obteniendo dominios`,
		gettingInfo: `Obteniendo tu información`,
		gettingLinks: `Obteniendo enlaces`,
		gettingPages: `Obteniendo páginas`,
		gettingPosts: `Obteniendo publicaciones`,
		gettingProfile: `Obteniendo tu perfil`,
		gettingThemes: `Obteniendo temas`,
		gettingTopics: `Obteniendo etiquetas`,
		gettingUploads: `Obteniendo subidas`,
		gettingUsers: `Obteniendo usuarios`,
		getTokens: `Obtener tokens`,
		givenApprovals: `Aprobaciones otorgadas`,
		goBack: `Regresar`,
		goToDomain: `Ir al dominio`,
		goToPayment: `Ir al pago`,
		goToSite: `Ir al sitio`,
		handle: `Identificador`,
		headers: `Encabezados`,
		help: `Ayuda`,
		helpCenter: `Centro de ayuda`,
		hhPlaceholder: `HH`,
		hideTools: `Ocultar herramientas`,
		hideYourRecords: `Ocultar tus registros`,
		home: `Inicio`,
		icon: `Icono`,
		iconDeleteConfirmation: `Sí, eliminar icono`,
		iconDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar el icono de tu sitio?`,
		iconUpdated: `Icono actualizado`,
		image: `Imagen`,
		images: `Imágenes`,
		immediately: `Inmediatamente`,
		inactiveComments: `Comentarios inactivos`,
		insertFromUrl: `Insertar desde URL`,
		insufficientBalance: `Saldo insuficiente. Agregar créditos para continuar.`,
		insufficientBalanceMessage: `Saldo insuficiente. Agregar créditos para continuar.`,
		insufficientTarioBalance: `Saldo tario insuficiente. Obtener tokens de testnet para continuar.`,
		invitePending: `Invitación pendiente`,
		invites: `Invitaciones`,
		invitesInfo: `¡Los siguientes portales te han invitado a unirte! Haz clic en el portal al que deseas unirte para comenzar.`,
		language: `Idioma`,
		larger: `Más grande`,
		layout: `Diseño`,
		layoutUpdated: `Diseño actualizado`,
		learn: `Aprender`,
		lease: `Arrendamiento`,
		leaseExtendedSuccessfully: `Arrendamiento extendido exitosamente.`,
		left: `Izquierda`,
		link: `Enlace`,
		linkAdded: `Enlace agregado`,
		linkDeleteConfirmation: `Sí, eliminar enlaces`,
		linkDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar los siguientes enlaces?`,
		linksUpdated: `Enlaces actualizados`,
		loading: `Cargando`,
		loadingDataFor: `Cargando datos para:`,
		loadingPortal: `Cargando tu portal`,
		loadingPost: `Cargando publicación`,
		loggingIn: `Iniciando sesión`,
		logo: `Logo`,
		logoAlt: `Logo`,
		logoDeleteConfirmation: `Sí, eliminar logo`,
		logoDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar el logo de tu sitio?`,
		logoUpdated: `Logo actualizado`,
		manage: `Administrar`,
		manageUser: `Administrar usuario`,
		max: `Máximo`,
		maxCharsReached: `Límite de caracteres alcanzado`,
		media: `Medios`,
		mediaDeleteConfirmation: `Sí, eliminar medios`,
		mediaDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar estos medios?`,
		mediaLibrary: `Biblioteca de medios`,
		mediaUpdated: `Medios actualizados`,
		mediaUploadCostInfo: `Se usarán créditos de tu saldo de subida para esta carga.`,
		mediaUploaded: `Medios subidos`,
		mediaUploadInfo: `Inserta medios desde una URL, sube nuevos medios o elige de tu biblioteca.`,
		missingPostFields: `Faltan algunos campos requeridos en esta publicación.`,
		mmPlaceholder: `MM`,
		moderation: `Moderación`,
		month: `Mes`,
		more: `Más`,
		moreActions: `Más acciones`,
		mostRead: `Más leídos`,
		myComments: `Mis comentarios`,
		myPosts: `Mis publicaciones`,
		myProfile: `Mi perfil`,
		myWallet: `Mi billetera`,
		name: `Nombre`,
		next: `Siguiente`,
		noCategoriesFound: `No se encontraron categorías`,
		noDomainsFound: `No se encontraron dominios`,
		noDomainsFoundInfo: `Los dominios se muestran aquí cuando existen en el ArNS de esta red y son propiedad de tu billetera.`,
		noExternalPortals: `No hay portales externos para contribuir`,
		noInactiveCommentsFound: `No se encontraron comentarios inactivos`,
		noInvites: `Sin invitaciones`,
		noInvitesInfo: `Actualmente no se encontraron invitaciones de portal para tu dirección de billetera o perfil.`,
		noInvitesProfileInfo: `Debes conectar tu billetera y crear un perfil para aceptar invitaciones.`,
		noLinksFound: `No se encontraron enlaces`,
		none: `Ninguno`,
		noPagesFound: `No se encontraron páginas`,
		noPortalsFound: `No se encontraron portales`,
		noPostsFound: `No se encontraron publicaciones`,
		noProfileFound: `No se encontró perfil asociado`,
		noRequestsFound: `No se encontraron solicitudes`,
		noThemesFound: `No se encontraron temas`,
		noTopicsFound: `No se encontraron etiquetas`,
		noUploadsFound: `No se encontraron subidas`,
		noUsersFound: `No se encontraron usuarios`,
		page: `Página`,
		pageNotFound: `Página no encontrada`,
		pages: `Páginas`,
		pageTitle: `Título de página`,
		pending: `Pendiente`,
		permanent: `Permanente`,
		permissionBaseDenied: `No tienes permiso para acceder a este portal`,
		permissionExternalContributor: `Eres un contribuidor externo en este portal. Verás este portal como una opción para contribuir desde tus otros portales.`,
		permissions: `Permisos`,
		pleaseReviewAndConfirm: `Por favor revisa y confirma`,
		portalCreate: `Crear un nuevo portal`,
		portalCreated: `Portal creado`,
		portalCreatingInfo: `Creando tu portal`,
		portalHeader: `Tu portal`,
		portalIconAlt: `Icono del portal`,
		portalReturn: `Volver al inicio del portal`,
		portals: `Portal`,
		portalsHeader: `Conectar a portal`,
		portalsInfo: `Tus portales aparecerán aquí`,
		portalsReturn: `Salir a todos los portales`,
		portalsSubheader: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor, Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
		portalUpdated: `Portal actualizado`,
		portalUpdatingInfo: `Actualizando tu portal`,
		post: `Publicación`,
		postApproved: `Publicación aprobada`,
		postCreateDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo`,
		postCreateHeader: `Crear una publicación`,
		postCreateSubheader: `Opciones de publicación`,
		posts: `Publicaciones`,
		postSaved: `Publicación guardada`,
		postsLink: `Ir a todas las publicaciones`,
		postStatusUpdated: `Estado de publicación actualizado`,
		postTitle: `Título de publicación`,
		postTopics: `Temas de publicación`,
		postUpdated: `Publicación actualizada`,
		prefill: `Rellenar automáticamente`,
		previous: `Anterior`,
		primaryDomain: `Dominio primario`,
		profile: `Perfil`,
		profileCreated: `Perfil creado`,
		profileCreatingInfo: `Creando tu perfil`,
		profileMenu: `Menú de perfil`,
		profileUpdated: `Perfil actualizado`,
		profileUpdatingInfo: `Actualizando tu perfil`,
		published: `Publicado`,
		publishTheme: `Publicar tema`,
		receivedApprovals: `Aprobaciones recibidas`,
		recentPosts: `Publicaciones recientes`,
		recommended: `Recomendado`,
		redirectFailed: `Error al redirigir el dominio:`,
		redirectSuccess: `¡Dominio redirigido correctamente al portal!`,
		registerDomain: `Registrar dominio`,
		registerErrorHeader: `Registro fallido`,
		registerErrorRetry: `Intentar de nuevo`,
		registeringProgress: `Registrando...`,
		registerStepCheckout: `Paso 3: Checkout`,
		registerStepFindName: `Paso 1: Encontrar un nombre`,
		registerStepPeriod: `Paso 2: Período de registro`,
		registerSuccessAnother: `Registrar otro dominio`,
		registerSuccessDomain: `Dominio:`,
		registerSuccessHeader: `¡Registro de dominio exitoso!`,
		registerSuccessTx: `ID de transacción:`,
		registerSuccessType: `Tipo:`,
		registrationFailed: `Registro fallido`,
		registrationPeriod: `Período de registro:`,
		registrationPeriodLabel: `Período de registro:`,
		reject: `Rechazar`,
		release: `Lanzar`,
		releaseDate: `Fecha de lanzamiento`,
		releaseDateUpdated: `Fecha de lanzamiento actualizada`,
		remaining: `Restante`,
		remainingAfterUpload: `Restante después de subir`,
		remove: `Eliminar`,
		removeAssignmentConfirm: `Eliminar Asignación de Dominio`,
		removeAssignmentConfirmMessage: `¿Estás seguro de que quieres eliminar este dominio del portal actual?`,
		removeAvatar: `Eliminar avatar`,
		removeBanner: `Eliminar banner`,
		removeCaption: `Eliminar descripción`,
		removeFromPortal: `Quitar del portal`,
		removeIcon: `Eliminar icono`,
		removeLogo: `Eliminar logo`,
		removeWallpaper: `Eliminar fondo de pantalla`,
		removingMedia: `Eliminando medios`,
		requests: `Solicitudes`,
		resolving: `Resolviendo`,
		returnHome: `Volver al inicio`,
		review: `Revisar`,
		reviewPost: `Revisar publicación`,
		reviewPostDetails: `Revisar detalles de publicación`,
		revoke: `Revocar`,
		right: `Derecha`,
		role: `Rol`,
		roleDescriptionAdmin: [
			'Actualizar configuración y diseño',
			'Agregar y eliminar medios',
			'Agregar y eliminar usuarios',
			'Agregar y eliminar publicaciones',
			'Aprobar publicaciones de contribuidores',
			'Eliminar comentarios de publicaciones',
			'Registrar dominios',
		],
		roleDescriptionContributor: ['Agregar solicitudes de publicación'],
		roleDescriptionExternalContributor: ['Agregar solicitudes de publicación desde otro portal'],
		roleDescriptionModerator: ['Aprobar publicaciones de contribuidores', 'Eliminar comentarios de publicaciones'],
		save: `Guardar`,
		saving: `Guardando`,
		seeLess: `Ver menos`,
		seeMore: `Ver más`,
		select: `Seleccionar`,
		selectParentCategory: `Seleccionar categoría padre`,
		selectPortal: `Selecciona tu portal`,
		setPrimaryDomain: `Establecer como dominio primario`,
		settings: `Configuración`,
		setup: `Configurar`,
		setupLink: `Ir a configuración completa`,
		shareCredits: `Compartir créditos`,
		showCaptionTools: `Mostrar herramientas de descripción`,
		showDomainActions: `Mostrar acciones de dominio`,
		showingRange: (start: number, end: number, total: number) => `Mostrando ${start} - ${end} de ${total}`,
		showYourRecords: `Mostrar tus registros`,
		sidebarClose: `Cerrar barra lateral`,
		sidebarOpen: `Abrir barra lateral`,
		siteCategories: `Categorías del sitio`,
		siteIconInfo: `Icono del sitio (Favicon) - Estándar: 32 × 32`,
		smaller: `Más pequeño`,
		socialLinks: `Enlaces del sitio`,
		sortBy: `Ordenar por`,
		sortNewestToOldest: `Más nuevo a más antiguo`,
		sortOldestToNewest: `Más antiguo a más nuevo`,
		status: `Estado`,
		submit: `Enviar`,
		successfullyFunded: `Fondeado exitosamente`,
		successfullyRevokedCredits: `Créditos revocados exitosamente`,
		summaryUpdated: `Resumen actualizado`,
		testnetMode: `Este es el modo testnet. Puedes obtener tokens tario del faucet de testnet.`,
		testnetModeMsg1: `Este es el modo testnet. Puedes obtener tokens tario del faucet de testnet.`,
		testnetModeMsg2: `Visita el faucet https://faucet.arweave.net/ para obtener tokens de prueba.`,
		text: `Texto`,
		themeDeleteConfirmation: `Sí, eliminar tema`,
		themeDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar el siguiente tema?`,
		themes: `Temas`,
		themesUpdated: `Tema actualizado`,
		thumbnailUpdated: `Miniatura actualizada`,
		time: `Tiempo`,
		toolkit: `Kit de herramientas`,
		top: `Superior`,
		topicAdded: `Tema agregado`,
		topicDeleteConfirmation: `Sí, eliminar temas`,
		topicDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar los siguientes temas?`,
		topics: `Temas`,
		topicsUpdated: `Temas actualizados`,
		totalDueLabel: `Total a pagar:`,
		toThisPortal: `A este portal`,
		transactionId: `Transacción ID`,
		unassigned: `No asignados`,
		unassignedAnt: `ANT sin asignar`,
		unassignedInfo: `Sin destino explícito. Asigna para dirigir a este portal.`,
		unauthorized: `No autorizado`,
		unauthorizedDomainManage: `Solo los administradores del portal pueden gestionar dominios.`,
		unauthorizedDomainRegister: `Solo los administradores del portal pueden registrar nombres de dominio.`,
		unauthorizedPortalUpdate: `Solo los administradores del portal pueden modificar la configuración del sitio.`,
		unauthorizedPortalUpdateMedia: `Solo los administradores del portal pueden agregar o eliminar medios.`,
		unauthorizedPostCreate: `Solo los administradores o contribuidores del portal pueden crear nuevas publicaciones.`,
		unauthorizedPostReview: `Solo los administradores o moderadores del portal pueden revisar publicaciones.`,
		unauthorizedUsersUpdate: `Solo los administradores del portal pueden agregar o modificar usuarios.`,
		untitledPost: `Publicación sin título`,
		updateAvailable: `Actualización disponible`,
		updating: `Actualizando`,
		updatingFonts: `Actualizando fuentes`,
		updatingLayout: `Actualizando diseño`,
		updatingPortal: `Actualizando portal`,
		updatingPostStatus: `Actualizando estado de publicación`,
		updatingTheme: `Actualizando tema`,
		upgradeToPermanentSuccessfully: `Actualizado a permanente exitosamente.`,
		upload: `Subir`,
		uploadAvatar: `Subir avatar`,
		uploadBanner: `Subir banner`,
		uploadCancelled: `Subida cancelada`,
		uploadFeaturedImage: `Subir imagen destacada`,
		uploadIcon: `Subir icono`,
		uploadingMedia: `Subiendo medios`,
		uploadLogo: `Subir logo (Recomendado 16 x 9)`,
		uploads: `Subidas`,
		uploadWallpaper: `Subir fondo de pantalla`,
		url: `URL`,
		urlPlaceholder: `https://`,
		usd: `USD`,
		user: `Usuario`,
		userAdded: `Usuario agregado`,
		userInviteInfo: `El usuario agregado verá esta invitación en su pantalla de inicio del portal.`,
		users: `Usuarios`,
		usersLink: `Ir a usuarios`,
		userUpdated: `Usuario actualizado`,
		validating: `validando…`,
		validationFailed: `Validación fallida`,
		validationFailedInfo: `No se pudieron validar estos dominios. Aparecen como no asignados hasta que se actualicen manualmente.`,
		validationFailedStatus: `Validación fallida - actualiza para reintentar`,
		video: `Video`,
		videos: `Videos`,
		view: `Ver`,
		viewInfo: `Ver información`,
		viewProfile: `Ver perfil`,
		visitFaucet: `Visitar faucet.`,
		waitingForProfile: `Esperando tu perfil`,
		wallet: `Billetera`,
		walletAddress: `Dirección de billetera`,
		walletOrPortalUnavailable: `Billetera no conectada o portal no disponible`,
		wallpaper: `Fondo de pantalla`,
		wallpaperDeleteConfirmation: `Sí, eliminar fondo de pantalla`,
		wallpaperDeleteConfirmationInfo: `¿Estás seguro de que deseas eliminar el fondo de pantalla de tu sitio?`,
		wallpaperUpdated: `Fondo de pantalla actualizado`,
		welcome: `Bienvenido`,
		year: `Año`,
		years: `Años`,
		youAreInvited: `Estás invitado`,
		yourUploadBalance: `Tu saldo de subida`,

		yyyyPlaceholder: `YYYY`,
	},
};
