export const language = {
	en: {
		add: `Add`,
		addCategory: `Add a category`,
		addTopic: `Add a topic`,
		alignCaption: `Align caption`,
		app: `Portals`,
		article: `Article`,
		bio: `Bio`,
		blocks: `Blocks`,
		blocksEmpty: `Start your post - Press enter, click here, or choose a block type`,
		bottom: `Bottom`,
		categories: `Categories`,
		chooseAppAppearance: `Choose app appearance`,
		close: `Close`,
		closeToolkit: `Close toolkit`,
		connect: `Connect`,
		connectWallet: `Connect your wallet`,
		connectToContinue: `Connect your wallet to continue`,
		copied: `Copied`,
		copyProfileAddress: `Copy profile address`,
		create: `Create`,
		createPortal: `Create a new portal`,
		createPost: `Create a post`,
		createProfile: `Create your profile`,
		delete: `Delete`,
		deleteBlock: `Delete block`,
		design: `Design`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		docs: `Docs`,
		domains: `Domains`,
		edit: `Edit`,
		editPortal: `Edit portal`,
		editPostTopics: `Edit post topics`,
		editProfile: `Edit your profile`,
		editSiteCategories: `Edit site categories`,
		editSiteLinks: `Edit site links`,
		errorUpdatingPortal: `Error updating portal`,
		errorUpdatingPost: `Error updating post`,
		errorUpdatingProfile: `Error updating profile`,
		fetching: `Fetching`,
		fetchingPortals: `Fetching portals`,
		gettingDomains: `Getting domains`,
		gettingInfo: `Getting your info`,
		gettingPosts: `Getting posts`,
		gettingTopics: `Getting topics`,
		gettingUsers: `Getting users`,
		goBack: `Go back`,
		goToSite: `Go to site`,
		handle: `Handle`,
		headers: `Headers`,
		helpCenter: `Help Center`,
		home: `Home`,
		image: `Image`,
		insertFromUrl: `Insert from URL`,
		layout: `Layout`,
		left: `Left`,
		loading: `Loading`,
		loadingPortal: `Loading your portal`,
		loadingPost: `Loading post`,
		maxCharsReached: `Max chars reached`,
		media: `Media`,
		mediaUploadInfo: `Upload media, choose from your library, or insert from a URL`,
		moreActions: `More actions`,
		name: `Name`,
		noDomainsFound: `No domains found`,
		noPostsFound: `No posts found`,
		noTopicsFound: `No topics found`,
		noUsersFound: `No users found`,
		pageNotFound: `Page not found`,
		portals: `Portals`,
		portalCreate: `Create a new portal`,
		portalCreated: `Portal created`,
		portalCreatingInfo: `Creating your portal`,
		portalHeader: `Your portal`,
		portalUpdated: `Portal updated`,
		portalsHeader: `Connect to Portals`,
		portalsInfo: `Your portals will be listed here`,
		portalUpdatingInfo: `Updating your portal`,
		portalReturn: `Return to portal home`,
		portalsReturn: `Exit to all portals`,
		portalsSubheader: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor, Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
		post: `Post`,
		posts: `Posts`,
		postCreateDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo`,
		postCreateHeader: `Create a post`,
		postCreateSubheader: `Post Options`,
		postSaved: `Post saved`,
		postTopics: `Post topics`,
		postUpdated: `Post updated`,
		profileCreated: `Profile created`,
		profileCreatingInfo: `Creating your profile`,
		profileMenu: `Profile menu`,
		profileUpdated: `Profile updated`,
		profileUpdatingInfo: `Updating your profile`,
		removeAvatar: `Remove avatar`,
		removeBanner: `Remove banner`,
		removeLogo: `Remove logo`,
		right: `Right`,
		save: `Save`,
		savingPost: `Saving your post`,
		selectParentCategory: `Select parent category`,
		sidebarClose: `Close sidebar`,
		sidebarOpen: `Open sidebar`,
		siteCategories: `Site categories`,
		siteLinks: `Site links`,
		selectPortal: `Select your portal`,
		settings: `Settings`,
		setup: `Setup`,
		text: `Text`,
		toolkit: `Toolkit`,
		top: `Top`,
		topics: `Topics`,
		untitledPost: `Untitled post`,
		upload: `Upload`,
		uploadAvatar: `Upload avatar`,
		uploadBanner: `Upload banner`,
		uploadLogo: `Upload logo`,
		users: `Users`,
		useDarkDisplay: `Use dark display`,
		useLightDisplay: `Use light display`,
		video: `Video`,
		viewInfo: `View info`,
		viewProfile: `View profile`,
		view: `View`,
		welcome: `Welcome`,
	},
};
