export const language = {
	en: {
		add: `Add`,
		addLink: `Add a link`,
		addCaption: `Add a caption`,
		addCategory: `Add a category`,
		addTheme: `Add a theme`,
		addTopic: `Add a topic`,
		addUser: `Add a user`,
		alignCaption: `Align caption`,
		all: `All`,
		amount: `Amount`,
		app: `Portal`,
		approve: `Approve`,
		appearance: `Appearance`,
		article: `Article`,
		author: `Author`,
		background: `Background`,
		bio: `Bio`,
		blocks: `Blocks`,
		blocksEmpty: `Start your post - Press enter, click here, or choose a block type`,
		bodyText: `Body Text`,
		bottom: `Bottom`,
		cancel: `Cancel`,
		caption: `Caption`,
		categories: `Categories`,
		categoriesUpdated: `Categories updated`,
		categoryAdded: `Category added`,
		categoryDeleteConfirmation: `Yes, remove categories`,
		categoryDeleteConfirmationInfo: `Are you sure you want to want to remove the following categories?`,
		categoryDuplicateError: `Duplicate category names found`,
		chooseAppAppearance: `Choose app appearance`,
		clear: `Clear`,
		close: `Close`,
		closeToolkit: `Close toolkit`,
		confirmDeletion: `Confirm deletion`,
		contribute: `Contribute`,
		conversion: `Conversion`,
		connect: `Connect`,
		connectWallet: `Connect your wallet`,
		connectToContinue: `Connect your wallet to continue`,
		convertToLink: `Convert to link`,
		colors: `Colors`,
		colorPicker: `Color Picker`,
		copied: `Copied`,
		copyProfileAddress: `Copy profile address`,
		costToUpload: `Cost to upload`,
		create: `Create`,
		created: `Created`,
		createPortal: `Create a new portal`,
		createPost: `Create a post`,
		createProfile: `Create your profile`,
		credits: `Credits`,
		current: `Current`,
		customAmount: `Custom Amount`,
		customAmountTurboInfo: `min $5 - max $10,000`,
		delete: `Delete`,
		deleteBlock: `Delete block`,
		deleteCaption: `Delete caption`,
		description: `Description`,
		design: `Design`,
		designLink: `Go to full designer`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		docs: `Docs`,
		domains: `Domains`,
		domainsLink: `Go to domains`,
		done: `Done`,
		draft: `Draft`,
		edit: `Edit`,
		editCaption: `Edit caption`,
		editDescription: `Edit Descripion`,
		editLink: `Edit link`,
		editPortal: `Edit portal`,
		editPostTopics: `Edit post topics`,
		editProfile: `Edit your profile`,
		editSiteCategories: `Edit site categories`,
		editSiteLinks: `Edit site links`,
		errorOccurred: `Error occurred`,
		errorUpdatingPortal: `Error updating portal`,
		errorUpdatingPost: `Error updating post`,
		errorUpdatingProfile: `Error updating profile`,
		errorUploadingThumbnail: `Error uploading thumbnail`,
		featuredImage: `Featured Image`,
		fetching: `Fetching`,
		fetchingPortals: `Fetching portals`,
		filter: `Filter`,
		filterBy: `Filter by`,
		fonts: `Fonts`,
		fontsUpdated: `Fonts updated`,
		fromLibrary: `Choose from library`,
		fund: `Fund`,
		fundTurboBalance: `Fund Turbo Balance`,
		fundTurboBalanceInfoHeader: `Buy Credits`,
		fundTurboBalanceInfoDetail: `Credits will be automatically added to your Turbo balance, and you can start using them right away.`,
		fundTurboPaymentHeader: `Complete Payment`,
		fundTurboPaymentDetail: `Payments are powered by ArDrive Turbo, and handled securely by Stripe.`,
		goToPayment: `Go to payment`,
		gettingCategories: `Getting categories`,
		gettingDomains: `Getting domains`,
		gettingInfo: `Getting your info`,
		gettingLinks: `Getting links`,
		gettingPosts: `Getting posts`,
		gettingProfile: `Getting your profile`,
		gettingThemes: `Getting themes`,
		gettingTopics: `Getting topics`,
		gettingUploads: `Getting uploads`,
		gettingUsers: `Getting users`,
		goBack: `Go back`,
		goToSite: `Go to site`,
		handle: `Handle`,
		headers: `Headers`,
		helpCenter: `Help Center`,
		hideTools: `Hide tools`,
		home: `Home`,
		image: `Image`,
		images: `Images`,
		insertFromUrl: `Insert from URL`,
		invites: `Invites`,
		invitesInfo: `The following portal(s) have invited you to join them ! Click on the portal you’d like to join to get started.`,
		language: `Language`,
		layout: `Layout`,
		learn: `Learn`,
		left: `Left`,
		link: `Link`,
		linkAdded: `Link added`,
		linkDeleteConfirmation: `Yes, remove links`,
		linkDeleteConfirmationInfo: `Are you sure you want to want to remove the following links?`,
		linksUpdated: `Links updated`,
		loading: `Loading`,
		loadingPortal: `Loading your portal`,
		loadingPost: `Loading post`,
		logoUpdated: `Logo updated`,
		loggingIn: `Logging in`,
		manage: `Manage`,
		manageUser: `Manage User`,
		max: `Max`,
		maxCharsReached: `Max chars reached`,
		media: `Media`,
		mediaDeleteConfirmation: `Yes, remove media`,
		mediaDeleteConfirmationInfo: `Are you sure you want to want to remove this media?`,
		mediaLibrary: `Media Library`,
		mediaUpdated: `Media updated`,
		mediaUploaded: `Media uploaded`,
		mediaUploadInfo: `Insert media from a URL, upload new media, or choose from your library.`,
		mediaUploadCostInfo: `Credits from your upload balance will be used for this upload.`,
		missingPostFields: `Some required fields are missing from this post.`,
		moreActions: `More actions`,
		name: `Name`,
		next: `Next`,
		none: `None`,
		noExternalPortals: `No external portals to contribute to`,
		noInvites: `No Invites`,
		noInvitesInfo: `Currently there are no portal invites found for your wallet address or profile.`,
		noInvitesProfileInfo: `You must connect your wallet and create a profile in order to accept invites.`,
		noCategoriesFound: `No categories found`,
		noDomainsFound: `No domains found`,
		noLinksFound: `No links found`,
		noPostsFound: `No posts found`,
		noPortalsFound: `No portals found`,
		noProfileFound: `No associated profile found`,
		noRequestsFound: `No requests found`,
		noThemesFound: `No themes found`,
		noTopicsFound: `No topics found`,
		noUploadsFound: `No uploads found`,
		noUsersFound: `No users found`,
		page: `Page`,
		pageNotFound: `Page not found`,
		permissionBaseDenied: `You do not have permission to access this portal`,
		permissionExternalContributor: `You are an external contributor on this portal. You will see this portal as an option to contribute to from your other portals.`,
		portals: `Portal`,
		portalCreate: `Create a new portal`,
		portalCreated: `Portal created`,
		portalCreatingInfo: `Creating your portal`,
		portalHeader: `Your portal`,
		portalUpdated: `Portal updated`,
		portalsHeader: `Connect to Portal`,
		portalsInfo: `Your portals will be listed here`,
		portalUpdatingInfo: `Updating your portal`,
		portalReturn: `Return to portal home`,
		portalsReturn: `Exit to all portals`,
		portalsSubheader: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor, Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
		post: `Post`,
		postTitle: `Post Title`,
		posts: `Posts`,
		postsLink: `Go to all posts`,
		postCreateDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo`,
		postCreateHeader: `Create a post`,
		postCreateSubheader: `Post Options`,
		postSaved: `Post saved`,
		postTopics: `Post topics`,
		postApproved: `Post approved`,
		postUpdated: `Post updated`,
		postStatusUpdated: `Post status updated`,
		prefill: `Prefill`,
		previous: `Previous`,
		profile: `Profile`,
		profileCreated: `Profile created`,
		profileCreatingInfo: `Creating your profile`,
		profileMenu: `Profile menu`,
		profileUpdated: `Profile updated`,
		profileUpdatingInfo: `Updating your profile`,
		published: `Published`,
		publishTheme: `Publish Theme`,
		reject: `Reject`,
		remainingAfterUpload: `Remaining after upload`,
		remove: `Remove`,
		removeAvatar: `Remove avatar`,
		removeBanner: `Remove banner`,
		removeCaption: `Remove caption`,
		removeLogo: `Remove logo`,
		removingMedia: `Removing media`,
		requests: `Requests`,
		returnHome: `Return home`,
		review: `Review`,
		reviewPostDetails: `Review post details`,
		right: `Right`,
		role: `Role`,
		save: `Save`,
		savingPost: `Saving your post`,
		selectParentCategory: `Select parent category`,
		sidebarClose: `Close sidebar`,
		sidebarOpen: `Open sidebar`,
		siteCategories: `Site categories`,
		siteLinks: `Site links`,
		siteLogo: `Site logo`,
		select: `Select`,
		selectPortal: `Select your portal`,
		settings: `Settings`,
		setup: `Setup`,
		setupLink: `Go to full setup`,
		showingRange: (start: number, end: number, total: number) => `Showing ${start} - ${end} of ${total}`,
		showCaptionTools: `Show caption tools`,
		sortBy: `Sort by`,
		sortNewestToOldest: `Newest to Oldest`,
		sortOldestToNewest: `Oldest to Newest`,
		submit: `Submit`,
		successfullyFunded: `Successfully funded`,
		summaryUpdated: `Summary updated`,
		text: `Text`,
		themes: `Themes`,
		themeUpdated: `Theme updated`,
		thumbnailUpdated: `Thumbnail updated`,
		toolkit: `Toolkit`,
		top: `Top`,
		topics: `Topics`,
		topicDeleteConfirmation: `Yes, remove topics`,
		topicDeleteConfirmationInfo: `Are you sure you want to want to remove the following topics?`,
		topicsUpdated: `Topics updated`,
		topicAdded: `Topic added`,
		unauthorized: `Unauthorized`,
		unauthorizedPortalUpdate: `Only portal admins can modify site setup.`,
		unauthorizedPostCreate: `Only portal admins or contributors can create new posts.`,
		unauthorizedPostReview: `Only portal admins or moderators can review posts.`,
		unauthorizedUsersUpdate: `Only portal admins can add or modify users.`,
		untitledPost: `Untitled post`,
		updating: `Updating`,
		updatingPostStatus: `Updating post status`,
		updatingFonts: `Updating fonts`,
		updatingTheme: `Updating theme`,
		upload: `Upload`,
		uploads: `Uploads`,
		uploadAvatar: `Upload avatar`,
		uploadBalance: `Upload balance`,
		uploadBanner: `Upload banner`,
		uploadCancelled: `Upload cancelled`,
		uploadFeaturedImage: `Upload Featured Image`,
		uploadLogo: `Upload Logo`,
		uploadingMedia: `Uploading Media`,
		url: `URL`,
		users: `Users`,
		userAdded: `User added`,
		userUpdated: `User updated`,
		usersLink: `Go to users`,
		video: `Video`,
		videos: `Videos`,
		viewInfo: `View info`,
		viewProfile: `View profile`,
		view: `View`,
		waitingForProfile: `Waiting for your profile`,
		walletAddress: `Wallet Address`,
		welcome: `Welcome`,
		yourUploadBalance: `Your upload balance`,
		youAreInvited: `You're invited`,
	},
};
