import { DefaultTheme } from 'styled-components';

export const lightTheme = {
	scheme: 'light',
	positive1: '#64B686',
	positive2: '#4EA673',
	negative1: '#E94278',
	negative2: '#E52461',
	neutral1: '#FFFFFF',
	neutral2: '#F9F9F9',
	neutral3: '#F0F0F0',
	neutral4: '#E4E4E4',
	neutral5: '#D6D6D6',
	neutral6: '#CCCCCC',
	neutral7: '#ADADAD',
	neutral8: '#A3A3A3',
	neutral9: '#8F8F8F',
	neutralA1: '#151515',
	neutralA2: '#333333',
	neutralA3: '#3D3D3D',
	neutralA4: '#474747',
	neutralA5: '#525252',
	neutralA6: '#666666',
	neutralA7: '#707070',
	overlay1: 'rgb(0, 0, 0, .45)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(220, 220, 220, .5)',
	primary1: '#5E66DB',
	primary2: '#454CB0',
	light1: '#FFFFFF',
	light2: '#DADADA',
	light3: '#B3B3B3',
	dark1: '#151515',
	dark2: '#333333',
};

export const darkTheme = {
	scheme: 'dark',
	positive1: '#38BD80',
	positive2: '#2F9D6A',
	labelAlt1: '#FFFFFF',
	negative1: '#D81E5B',
	negative2: '#E43A72',
	neutral1: '#1B1B1B',
	neutral2: '#202020',
	neutral3: '#2D2D2D',
	neutral4: '#2F2F2F',
	neutral5: '#3D3D3D',
	neutral6: '#474747',
	neutral7: '#525252',
	neutral8: '#5C5C5C',
	neutral9: '#666666',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CFCFCF',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	overlay1: 'rgb(0, 0, 0, .35)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(0, 0, 0, .5)',
	primary1: '#5E66DB',
	primary2: '#454CB0',
	light1: '#FFFFFF',
	light2: '#DADADA',
	light3: '#B3B3B3',
	dark1: '#151515',
	dark2: '#333333',
};

export const darkThemeAlt1 = {
	scheme: 'dark',
	positive1: '#38BD80',
	positive2: '#2F9D6A',
	labelAlt1: '#FFFFFF',
	negative1: '#D81E5B',
	negative2: '#E43A72',
	neutral1: '#181920',
	neutral2: '#1D1E24',
	neutral3: '#23242A',
	neutral4: '#282930',
	neutral5: '#2E2F36',
	neutral6: '#34353C',
	neutral7: '#3A3B42',
	neutral8: '#404148',
	neutral9: '#47484F',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CFCFCF',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	overlay1: 'rgb(0, 0, 0, .35)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(0, 0, 0, .5)',
	primary1: '#5E66DB',
	primary2: '#454CB0',
	light1: '#FFFFFF',
	light2: '#DADADA',
	light3: '#B3B3B3',
	dark1: '#151515',
	dark2: '#333333',
};

export const darkThemeAlt2 = {
	scheme: 'dark',
	positive1: '#38BD80',
	positive2: '#2F9D6A',
	labelAlt1: '#FFFFFF',
	negative1: '#D81E5B',
	negative2: '#E43A72',
	neutral1: '#111216',
	neutral2: '#15161A',
	neutral3: '#1A1B20',
	neutral4: '#1E1F24',
	neutral5: '#22232A',
	neutral6: '#27282F',
	neutral7: '#2C2D34',
	neutral8: '#313239',
	neutral9: '#36363F',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CFCFCF',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	overlay1: 'rgb(0, 0, 0, .35)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(0, 0, 0, .5)',
	primary1: '#5E66DB',
	primary2: '#454CB0',
	light1: '#FFFFFF',
	light2: '#DADADA',
	light3: '#B3B3B3',
	dark1: '#151515',
	dark2: '#333333',
};

export const theme = (currentTheme: any): DefaultTheme => ({
	scheme: currentTheme.scheme,
	colors: {
		accordion: {
			background: currentTheme.neutral1,
			hover: currentTheme.neutral2,
			color: currentTheme.neutralA1,
		},
		border: {
			primary: currentTheme.neutral4,
			alt1: currentTheme.neutral5,
			alt2: currentTheme.neutral6,
			alt3: currentTheme.neutral7,
			alt4: currentTheme.neutral9,
			alt5: currentTheme.primary1,
			alt6: currentTheme.primary2,
		},
		button: {
			primary: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral4,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral8,
					color: currentTheme.neutralA1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt1: {
				background: currentTheme.primary1,
				border: currentTheme.primary1,
				color: currentTheme.light1,
				active: {
					background: currentTheme.primary2,
					border: currentTheme.primary2,
					color: currentTheme.light1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt2: {
				background: currentTheme.neutralA1,
				border: currentTheme.neutralA1,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutralA4,
					border: currentTheme.neutralA4,
					color: currentTheme.neutralA4,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
		},
		checkbox: {
			active: {
				background: currentTheme.primary2,
			},
			background: currentTheme.neutral1,
			hover: currentTheme.neutral3,
			disabled: currentTheme.neutral5,
		},
		container: {
			primary: {
				background: currentTheme.neutral1,
				active: currentTheme.neutral3,
			},
			alt1: {
				background: currentTheme.neutral2,
			},
			alt2: {
				background: currentTheme.neutral3,
			},
			alt3: {
				background: currentTheme.neutral4,
			},
			alt4: {
				background: currentTheme.neutral5,
			},
			alt5: {
				background: currentTheme.neutralA4,
			},
			alt6: {
				background: currentTheme.primary1,
			},
			alt7: {
				background: currentTheme.neutralA3,
			},
			alt8: {
				background: currentTheme.dark1,
			},
			alt9: {
				background: currentTheme.primary1,
			},
			alt10: {
				background: currentTheme.primary2,
			},
		},
		font: {
			primary: currentTheme.neutralA1,
			alt1: currentTheme.neutralA5,
			alt2: currentTheme.neutralA4,
			alt3: currentTheme.neutral8,
			alt4: currentTheme.neutral1,
			alt5: currentTheme.primary1,
			light1: currentTheme.light1,
			light2: currentTheme.light2,
			light3: currentTheme.light3,
			dark1: currentTheme.dark1,
			dark2: currentTheme.dark2,
		},
		form: {
			background: currentTheme.neutral1,
			border: currentTheme.neutral4,
			invalid: {
				outline: currentTheme.negative1,
				shadow: currentTheme.negative2,
			},
			valid: {
				outline: currentTheme.primary1,
				shadow: currentTheme.primary2,
			},
			disabled: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral5,
				label: currentTheme.neutralA2,
			},
		},
		gradient: {
			start: currentTheme.primary1,
			middle: currentTheme.primary1,
			end: currentTheme.primary2,
		},
		icon: {
			primary: {
				fill: currentTheme.neutralA4,
				active: currentTheme.neutral4,
				disabled: currentTheme.neutralA3,
			},
			alt1: {
				fill: currentTheme.neutral4,
				active: currentTheme.neutral5,
				disabled: currentTheme.neutral3,
			},
			alt2: {
				fill: currentTheme.neutralA1,
				active: currentTheme.neutralA4,
				disabled: currentTheme.neutral3,
			},
			alt3: {
				fill: currentTheme.neutralA2,
				active: currentTheme.neutral1,
				disabled: currentTheme.neutral3,
			},
		},
		indicator: {
			active: currentTheme.positive1,
		},
		link: {
			color: currentTheme.neutralA1,
			active: currentTheme.neutralA4,
		},
		loader: {
			primary: currentTheme.primary1,
		},
		overlay: {
			primary: currentTheme.overlay1,
			alt1: currentTheme.overlay2,
		},
		row: {
			active: {
				background: currentTheme.neutral3,
				border: currentTheme.neutral2,
			},
			hover: {
				background: currentTheme.neutral2,
			},
		},
		scrollbar: {
			track: currentTheme.neutral2,
			thumb: currentTheme.neutral5,
		},
		shadow: {
			primary: currentTheme.shadow1,
		},
		tabs: {
			color: currentTheme.neutralA4,
			active: {
				background: currentTheme.primary1,
				color: currentTheme.neutralA1,
			},
		},
		tooltip: {
			background: currentTheme.dark2,
			border: currentTheme.dark2,
			color: currentTheme.light1,
		},
		view: {
			background: currentTheme.neutral1,
		},
		warning: {
			primary: currentTheme.negative1,
			alt1: currentTheme.negative2,
		},
	},
	typography: {
		family: {
			primary: `'Lato', system-ui`,
			alt1: `'Merriweather', serif`,
		},
		size: {
			xxxSmall: '12px',
			xxSmall: '13px',
			xSmall: '14px',
			small: '15px',
			base: '16px',
			lg: '18px',
			xLg: '24px',
			h1: 'clamp(32px, 2.85vw, 48px)',
			h2: 'clamp(28px, 2.45vw, 44px)',
			h4: 'clamp(24px, 2vw, 36px)',
		},
		weight: {
			light: '300',
			medium: '500',
			bold: '600',
			xBold: '700',
			xxBold: '800',
		},
	},
});
