import * as React from 'react';

import { ReactSVG } from 'components/atoms/GatewaySVG';
import { ICONS } from 'helpers/config';

import * as S from './styles';

interface EmojiPickerProps {
	onInsertEmoji: (emoji: string) => void;
}

export default function EmojiPicker({ onInsertEmoji }: EmojiPickerProps) {
	const [isVisible, setIsVisible] = React.useState(false);
	const [emojiSearch, setEmojiSearch] = React.useState('');
	const [selectedCategory, setSelectedCategory] = React.useState('smileys');
	const emojiPickerRef = React.useRef<HTMLDivElement>(null);
	const emojiButtonRef = React.useRef<HTMLDivElement>(null);

	const onClose = () => setIsVisible(false);

	React.useEffect(() => {
		const handleClickOutside = (event: MouseEvent) => {
			if (
				emojiPickerRef.current &&
				!emojiPickerRef.current.contains(event.target as Node) &&
				emojiButtonRef.current &&
				!emojiButtonRef.current.contains(event.target as Node)
			) {
				onClose();
			}
		};

		if (isVisible) {
			document.addEventListener('mousedown', handleClickOutside);
			return () => {
				document.removeEventListener('mousedown', handleClickOutside);
			};
		}
	}, [isVisible, onClose]);

	const handleEmoji = (emoji: string) => {
		onInsertEmoji(emoji);
		onClose();
		setEmojiSearch('');
	};

	const emojiMap = {
		'😀': ['grinning', 'face', 'smile', 'happy'],
		'😃': ['smiley', 'face', 'happy', 'joy', 'haha'],
		'😄': ['smile', 'face', 'happy', 'joy', 'laugh', 'pleased'],
		'😁': ['grin', 'face', 'happy', 'smile', 'joy'],
		'😅': ['sweat', 'smile', 'face', 'happy', 'laugh', 'relief'],
		'😂': ['joy', 'face', 'cry', 'laugh', 'happy', 'tears'],
		'🤣': ['rofl', 'laugh', 'rolling', 'floor', 'face', 'happy'],
		'😊': ['blush', 'face', 'smile', 'happy', 'pleased'],
		'😇': ['halo', 'face', 'angel', 'innocent', 'smile'],
		'🙂': ['smile', 'face', 'happy', 'pleased'],
		'😉': ['wink', 'face', 'happy', 'flirt'],
		'😌': ['relieved', 'face', 'happy', 'relaxed'],
		'😍': ['love', 'face', 'heart', 'eyes', 'smile'],
		'🥰': ['love', 'face', 'smile', 'heart', 'happy'],
		'😘': ['kiss', 'face', 'love', 'smile'],
		'😋': ['yum', 'face', 'happy', 'tongue', 'smile'],
		'😛': ['tongue', 'face', 'happy', 'silly'],
		'😜': ['wink', 'tongue', 'face', 'happy', 'silly'],
		'🤪': ['zany', 'face', 'silly', 'crazy', 'tongue'],
		'😝': ['tongue', 'face', 'happy', 'silly', 'wink'],
		'🤔': ['thinking', 'face', 'consider', 'hmm'],
		'😐': ['neutral', 'face', 'meh'],
		'😑': ['expressionless', 'face', 'blank'],
		'😶': ['no', 'mouth', 'face', 'quiet', 'silent'],
		'😏': ['smirk', 'face', 'smile'],
		'😒': ['unamused', 'face', 'meh'],
		'🙄': ['eye', 'roll', 'face', 'whatever'],
		'😬': ['grimace', 'face', 'awkward'],
		'😔': ['pensive', 'face', 'sad', 'depressed'],
		'😪': ['sleepy', 'face', 'tired'],
		'😴': ['sleeping', 'face', 'tired', 'sleep'],
		'😷': ['mask', 'face', 'sick', 'ill'],
		'🤒': ['thermometer', 'face', 'sick', 'fever'],
		'🤕': ['bandage', 'face', 'hurt', 'injured'],
		'🤢': ['nausea', 'face', 'sick', 'vomit'],
		'🤮': ['vomit', 'face', 'sick', 'puke'],
		'🤧': ['sneeze', 'face', 'gesundheit', 'sick'],
		'😵': ['dizzy', 'face', 'spent'],
		'🤯': ['mind', 'blown', 'face', 'exploding', 'head'],
		'😎': ['cool', 'face', 'sunglasses'],
		'🤓': ['nerd', 'face', 'glasses'],
		'😕': ['confused', 'face', 'meh'],
		'😟': ['worried', 'face', 'concern'],
		'🙁': ['frown', 'face', 'sad'],
		'☹️': ['frown', 'face', 'sad'],
		'😮': ['surprise', 'face', 'impressed', 'wow'],
		'😯': ['hushed', 'face', 'woo', 'shock'],
		'😲': ['astonished', 'face', 'xox', 'surprised', 'gasps'],
		'😳': ['flushed', 'face', 'blush', 'shy', 'flattered'],
		'😦': ['frowning', 'face', 'aw', 'what'],
		'😧': ['anguished', 'face', 'stunned', 'nervous'],
		'😨': ['fearful', 'face', 'scared', 'terrified'],
		'😰': ['cold', 'sweat', 'face', 'nervous', 'sweat'],
		'😥': ['sad', 'relieved', 'face', 'phew', 'sweat', 'nervous'],
		'😢': ['cry', 'face', 'tear', 'sad', 'depressed', 'upset'],
		'😭': ['sob', 'face', 'cry', 'tears', 'sad'],
		'😱': ['scream', 'face', 'munch', 'scared', 'omg'],
		'😖': ['confounded', 'face', 'sick', 'unwell', 'oops'],
		'😣': ['persevere', 'face', 'sick', 'no', 'upset'],
		'😞': ['disappointed', 'face', 'sad'],
		'😓': ['sweat', 'face', 'hot', 'sad', 'tired'],
		'😩': ['weary', 'face', 'tired', 'sleepy'],
		'😫': ['tired', 'face', 'sick', 'whine'],
		'😤': ['triumph', 'face', 'gas', 'phew', 'proud'],
		'😡': ['rage', 'face', 'angry', 'mad', 'hate'],
		'😠': ['angry', 'face', 'mad', 'annoyed'],
		'😈': ['devil', 'face', 'horns', 'evil'],
		'👿': ['imp', 'devil', 'face', 'angry', 'horns'],
		'💀': ['skull', 'dead', 'skeleton', 'creepy', 'death'],
		'☠️': ['skull', 'crossbones', 'dead', 'pirate'],
		'💩': ['poop', 'hankey', 'shitface', 'fail'],
		'🤡': ['clown', 'face'],
		'👋': ['wave', 'hands', 'gesture', 'goodbye', 'solong', 'farewell'],
		'🤚': ['raised', 'back', 'hand', 'fingers', 'raised'],
		'🖐️': ['hand', 'fingers', 'stop', 'highfive'],
		'✋': ['hand', 'fingers', 'stop', 'highfive', 'palm'],
		'👌': ['ok', 'hand', 'fingers', 'limbs'],
		'✌️': ['victory', 'fingers', 'ohyeah', 'hand', 'peace'],
		'🤞': ['crossed', 'fingers', 'good', 'luck'],
		'👈': ['point', 'left', 'direction', 'fingers', 'hand'],
		'👉': ['point', 'right', 'fingers', 'direction', 'hand'],
		'👆': ['point', 'up', 'hand', 'fingers', 'direction'],
		'👇': ['point', 'down', 'fingers', 'hand', 'direction'],
		'👍': ['thumbsup', 'yes', 'awesome', 'good', 'agree'],
		'👎': ['thumbsdown', 'no', 'dislike', 'hand'],
		'✊': ['fist', 'hand', 'fingers'],
		'👊': ['fist', 'oncoming', 'limbs', 'attack', 'hand'],
		'👏': ['clap', 'hands', 'praise', 'applause'],
		'🙌': ['raised', 'hands', 'gesture', 'hooray'],
		'🙏': ['pray', 'hands', 'gesture', 'namaste', 'please'],
		'💪': ['muscle', 'strong', 'biceps', 'flex', 'hand'],
		'🐶': ['dog', 'animal', 'friend', 'nature', 'woof', 'puppy', 'pet'],
		'🐱': ['cat', 'animal', 'meow', 'pet', 'cats'],
		'🐭': ['mouse', 'animal', 'nature', 'cheese', 'wedge', 'rodent'],
		'🐹': ['hamster', 'animal', 'nature'],
		'🐰': ['rabbit', 'animal', 'nature', 'pet', 'spring', 'easter', 'bunny'],
		'🦊': ['fox', 'animal', 'nature', 'face'],
		'🐻': ['bear', 'animal', 'nature', 'wild'],
		'🐼': ['panda', 'animal', 'nature', 'panda'],
		'🐨': ['koala', 'animal', 'nature'],
		'🐯': ['tiger', 'animal', 'cat', 'danger', 'wild', 'nature'],
		'🦁': ['lion', 'animal', 'nature', 'cat'],
		'🐮': ['cow', 'beef', 'ox', 'animal', 'nature'],
		'🐷': ['pig', 'animal', 'oink', 'nature'],
		'🐸': ['frog', 'animal', 'nature', 'croak', 'toad'],
		'🐵': ['monkey', 'animal', 'nature', 'banana', 'circus'],
		'🐔': ['chicken', 'animal', 'cluck', 'nature', 'bird'],
		'🐧': ['penguin', 'animal', 'nature'],
		'🐦': ['bird', 'animal', 'nature', 'fly', 'tweet', 'spring'],
		'🦋': ['butterfly', 'animal', 'insect', 'nature', 'caterpillar'],
		'🐌': ['snail', 'slow', 'animal', 'shell'],
		'🐞': ['beetle', 'insect', 'bug', 'ladybird'],
		'🐜': ['ant', 'animal', 'insect', 'nature', 'bug'],
		'🐝': ['bee', 'animal', 'insect', 'nature', 'bug', 'spring', 'honey'],
		'🦂': ['scorpion', 'animal', 'arachnid'],
		'🐢': ['turtle', 'slow', 'animal', 'nature'],
		'🐍': ['snake', 'animal', 'evil', 'nature', 'hiss', 'python'],
		'🐙': ['octopus', 'animal', 'creature', 'ocean', 'sea', 'nature'],
		'🐠': ['fish', 'animal', 'food', 'nature'],
		'🐟': ['fish', 'animal', 'food', 'nature'],
		'🐬': ['dolphin', 'animal', 'nature', 'fish', 'sea', 'ocean', 'flipper'],
		'🐳': ['whale', 'animal', 'nature', 'sea', 'ocean'],
		'🐋': ['whale', 'animal', 'nature', 'sea', 'ocean'],
		'🦈': ['shark', 'animal', 'nature', 'fish', 'sea', 'ocean', 'jaws'],
		'🐊': ['crocodile', 'animal', 'nature', 'reptile', 'lizard', 'alligator'],
		'🐘': ['elephant', 'animal', 'nature', 'nose', 'th', 'circus'],
		'🐪': ['camel', 'animal', 'hot', 'desert', 'hump'],
		'🦒': ['giraffe', 'animals', 'nature', 'spots', 'safari'],
		'🐕': ['dog', 'animal', 'nature', 'friend', 'doge', 'pet', 'faithful'],
		'🐈': ['cat', 'animal', 'meow', 'nature', 'pet', 'kitten'],
		'🦃': ['turkey', 'animal', 'bird'],
		'🕊️': ['dove', 'animal', 'bird'],
		'🐇': ['rabbit', 'animal', 'nature', 'pet', 'magic', 'spring'],
		'🐁': ['mouse', 'animal', 'nature', 'rodent'],
		'🐀': ['rat', 'animal', 'mouse', 'rodent'],
		'🍏': ['apple', 'fruit', 'mac', 'school'],
		'🍎': ['apple', 'fruit', 'red', 'food'],
		'🍐': ['pear', 'fruit', 'nature', 'food'],
		'🍊': ['orange', 'fruit', 'food', 'nature'],
		'🍋': ['lemon', 'fruit', 'nature', 'yellow'],
		'🍌': ['banana', 'fruit', 'food', 'monkey'],
		'🍉': ['watermelon', 'fruit', 'food', 'picnic', 'summer'],
		'🍇': ['grapes', 'fruit', 'food', 'wine'],
		'🍓': ['strawberry', 'fruit', 'food', 'nature'],
		'🍈': ['melon', 'fruit', 'nature', 'food'],
		'🍒': ['cherries', 'food', 'fruit'],
		'🍑': ['peach', 'fruit', 'nature', 'food'],
		'🥭': ['mango', 'fruit', 'food', 'tropical'],
		'🍍': ['pineapple', 'fruit', 'nature', 'food'],
		'🥝': ['kiwi', 'fruit', 'food'],
		'🍅': ['tomato', 'fruit', 'vegetable', 'nature', 'food'],
		'🍆': ['eggplant', 'vegetable', 'nature', 'food', 'aubergine'],
		'🥑': ['avocado', 'fruit', 'food'],
		'🥦': ['broccoli', 'fruit', 'food', 'vegetable'],
		'🥒': ['cucumber', 'fruit', 'food', 'pickle'],
		'🌽': ['corn', 'food', 'vegetable', 'ear'],
		'🥕': ['carrot', 'vegetable', 'food'],
		'🧄': ['garlic', 'food', 'spice', 'cook'],
		'🧅': ['onion', 'cook', 'food', 'spice'],
		'🥔': ['potato', 'food', 'tuber', 'vegatable', 'starch'],
		'🍠': ['sweet', 'potato', 'food', 'nature'],
		'🥐': ['croissant', 'food', 'bread', 'french'],
		'🍞': ['bread', 'food', 'wheat', 'breakfast', 'toast'],
		'🥖': ['baguette', 'food', 'bread', 'french'],
		'🧀': ['cheese', 'food', 'chaddar', 'swiss'],
		'🥚': ['egg', 'food', 'chicken', 'breakfast'],
		'🥓': ['bacon', 'food', 'breakfast', 'pork', 'pig', 'meat'],
		'🥩': ['steak', 'food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop'],
		'🍗': ['poultry', 'leg', 'food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey'],
		'🍖': ['meat', 'food', 'cow', 'pig', 'animal'],
		'🌭': ['hotdog', 'food', 'frankfurter', 'america'],
		'🍔': ['hamburger', 'meat', 'fast', 'food', 'beef', 'cheeseburger', 'mcdonalds', 'burger', 'king'],
		'🍟': ['fries', 'food', 'fast', 'food', 'mcdonalds', 'salt', 'potato'],
		'🍕': ['pizza', 'food', 'party', 'italy'],
		'🌮': ['taco', 'food', 'mexican'],
		'🌯': ['burrito', 'food', 'mexican'],
		'🥗': ['salad', 'food', 'healthy', 'lettuce'],
		'🥘': ['paella', 'food', 'spanish', 'shallow', 'pan'],
		'🍝': ['spaghetti', 'food', 'italian', 'pasta', 'noodle'],
		'🍜': ['ramen', 'food', 'japanese', 'noodle', 'chopsticks'],
		'🍲': ['stew', 'food', 'meat', 'soup'],
		'🍛': ['curry', 'food', 'spicy', 'hot', 'indian'],
		'🍣': ['sushi', 'food', 'fish', 'japanese', 'rice'],
		'🍱': ['bento', 'food', 'japanese', 'box'],
		'🍤': ['fried', 'shrimp', 'food', 'animal', 'appetizer', 'summer'],
		'🍙': ['rice', 'ball', 'food', 'japanese'],
		'🍚': ['rice', 'food', 'china', 'asian'],
		'🍘': ['rice', 'cracker', 'food', 'japanese'],
		'🍥': [
			'fish',
			'cake',
			'food',
			'japan',
			'sea',
			'beach',
			'narutomaki',
			'pink',
			'swirl',
			'kamaboko',
			'surimi',
			'ramen',
		],
		'🍢': ['oden', 'food', 'japanese'],
		'🍡': ['dango', 'food', 'japanese'],
		'🧁': ['cupcake', 'food', 'dessert', 'cake'],
		'🍰': ['cake', 'food', 'dessert'],
		'🎂': ['birthday', 'cake', 'food', 'dessert', 'wish'],
		'🍮': ['custard', 'dessert', 'food'],
		'🍭': ['lollipop', 'food', 'dessert', 'candy', 'sweet', 'sugar'],
		'🍬': ['candy', 'snack', 'dessert', 'sweet', 'lolly'],
		'🍫': ['chocolate', 'food', 'dessert'],
		'🍿': ['popcorn', 'food', 'movie', 'theater', 'films', 'snack'],
		'🍩': ['doughnut', 'food', 'dessert', 'snack', 'sweet', 'donut'],
		'🍪': ['cookie', 'food', 'snack', 'oreo', 'chocolate', 'sweet', 'dessert'],
		'⚽': ['soccer', 'sports', 'football'],
		'🏀': ['basketball', 'sports', 'balls'],
		'🏈': ['football', 'sports', 'balls', 'NFL'],
		'⚾': ['baseball', 'sports', 'balls'],
		'🎾': ['tennis', 'sports', 'balls', 'green'],
		'🏐': ['volleyball', 'sports', 'balls'],
		'🏉': ['rugby', 'football', 'sports', 'team'],
		'🎱': ['pool', '8ball', 'game', 'play', 'billiards'],
		'🏓': ['ping', 'pong', 'sports', 'pingpong', 'table', 'tennis'],
		'🏸': ['badminton', 'sports'],
		'🏆': ['trophy', 'win', 'award', 'contest', 'place'],
		'🥇': ['gold', 'medal', 'first', 'winner', 'award'],
		'🥈': ['silver', 'medal', 'second', 'award'],
		'🥉': ['bronze', 'medal', 'third', 'award'],
		'🏅': ['medal', 'award', 'winning', 'first'],
		'🎖️': ['medal', 'award', 'winning', 'army'],
		'🎗️': ['reminder', 'ribbon', 'sports'],
		'🎫': ['ticket', 'event', 'concert', 'pass'],
		'🎟️': ['ticket', 'event', 'concert', 'pass'],
		'🎪': ['circus', 'carnival', 'party', 'round', 'tent'],
		'🎭': ['theater', 'art', 'acting'],
		'🎨': ['art', 'design', 'paint', 'draw', 'colors'],
		'🎬': ['clapper', 'movie', 'film', 'record'],
		'🎤': ['microphone', 'sound', 'music', 'PA', 'sing', 'karaoke'],
		'🎧': ['headphones', 'music', 'score', 'gadgets'],
		'🎼': ['musical', 'score', 'treble', 'clef', 'compose'],
		'🎹': ['musical', 'keyboard', 'piano', 'instrument', 'compose'],
		'🥁': ['drum', 'music', 'instrument', 'drumsticks', 'snare'],
		'🎷': ['saxophone', 'music', 'instrument', 'jazz', 'blues'],
		'🎺': ['trumpet', 'music', 'brass'],
		'🎸': ['guitar', 'music', 'instrument'],
		'🎻': ['violin', 'music', 'instrument', 'orchestra', 'symphony'],
		'🎲': ['dice', 'random', 'tabletop', 'play', 'luck'],
		'🎯': ['direct', 'hit', 'game', 'play', 'bar', 'target', 'bullseye'],
		'🎳': ['bowling', 'sports', 'fun', 'play'],
		'🎮': ['video', 'game', 'play', 'console', 'PS4', 'controller'],
		'🎰': ['slot', 'machine', 'bet', 'gamble', 'vegas', 'fruit', 'machine', 'luck', 'casino'],
		'🚗': ['car', 'automobile', 'vehicle', 'transportation', 'red'],
		'🚕': ['taxi', 'uber', 'vehicle', 'cars', 'transportation'],
		'🚙': ['blue', 'car', 'vehicle', 'transportation'],
		'🚌': ['bus', 'vehicle', 'transportation'],
		'🚎': ['trolleybus', 'bart', 'transportation', 'vehicle'],
		'🏎️': ['racing', 'car', 'sports', 'race', 'fast', 'formula'],
		'🚓': ['police', 'car', 'vehicle', 'cars', 'transportation', 'law', 'legal', 'enforcement'],
		'🚑': ['ambulance', 'health', '911', 'hospital'],
		'🚒': ['fire', 'engine', 'transportation', 'truck'],
		'🚐': ['minibus', 'vehicle', 'car', 'transportation'],
		'🚚': ['truck', 'transportation', 'vehicle'],
		'🚛': ['truck', 'vehicle', 'cars', 'transportation'],
		'🚜': ['tractor', 'vehicle', 'car', 'farming', 'agriculture'],
		'🚲': ['bicycle', 'sports', 'bike', 'exercise', 'hipster'],
		'🏍️': ['motorcycle', 'race', 'sports', 'fast'],
		'✈️': ['airplane', 'vehicle', 'transportation', 'fly', 'travel'],
		'🚁': ['helicopter', 'transportation', 'vehicle', 'fly'],
		'🛶': ['canoe', 'boat', 'paddle', 'water', 'ship'],
		'⛵': ['boat', 'resort', 'sea', 'vehicle', 'yacht'],
		'🚤': ['speedboat', 'ship', 'transportation', 'vehicle', 'summer'],
		'🛥️': ['motor', 'boat', 'ship'],
		'🚢': ['ship', 'transportation', 'titanic', 'deploy'],
		'⚓': ['anchor', 'link', 'boat', 'ship'],
		'🏠': ['house', 'building', 'home'],
		'🏡': ['house', 'building', 'home'],
		'🏘️': ['houses', 'buildings', 'photo'],
		'🏚️': ['house', 'abandon', 'evict', 'broken', 'building'],
		'🏗️': ['building', 'construction', 'wip'],
		'🏭': ['factory', 'building', 'industry', 'pollution', 'smoke'],
		'🏢': ['office', 'building', 'bureau', 'work'],
		'🏬': ['department', 'store', 'building', 'shop', 'mall'],
		'🏣': ['post', 'office', 'building', 'email'],
		'🏤': ['post', 'office', 'building', 'email'],
		'🏥': ['hospital', 'building', 'health', 'surgery', 'doctor'],
		'🏦': ['bank', 'building', 'money', 'sales', 'cash', 'business', 'enterprise'],
		'🏨': ['hotel', 'building', 'accomodation', 'checkin'],
		'🏪': ['convenience', 'store', 'building'],
		'🏫': ['school', 'building', 'student', 'education', 'learn', 'teach'],
		'🏩': ['love', 'hotel', 'like', 'affection', 'dating'],
		'💒': ['wedding', 'love', 'like', 'affection', 'couple', 'marriage', 'bride', 'groom'],
		'⛪': ['church', 'building', 'religion', 'christ'],
		'🕌': ['mosque', 'islam', 'worship', 'minaret'],
		'🕍': ['synagogue', 'jewish', 'worship', 'temple', 'jew'],
		'⛩️': ['shinto', 'shrine', 'japan', 'kyoto', 'gate'],
		'🗼': ['tokyo', 'tower', 'japan'],
		'🗽': ['statue', 'liberty', 'american', 'newyork'],
		'⌚': ['watch', 'time', 'accessories'],
		'📱': ['mobile', 'phone', 'technology', 'apple', 'gadgets', 'dial'],
		'📲': ['mobile', 'phone', 'call', 'incoming'],
		'💻': ['computer', 'technology', 'laptop', 'screen', 'display', 'monitor'],
		'⌨️': ['keyboard', 'technology', 'computer', 'type', 'input', 'text'],
		'🖥️': ['desktop', 'computer', 'technology', 'computing', 'screen'],
		'🖨️': ['printer', 'paper', 'ink'],
		'🖱️': ['mouse', 'click', 'computer', 'technology'],
		'💽': ['minidisc', 'technology', 'record', 'data', 'disk', '90s'],
		'💾': ['floppy', 'disk', 'oldschool', 'technology', 'save', '90s', 'data'],
		'💿': ['cd', 'technology', 'dvd', 'disk', 'disc', '90s'],
		'📀': ['dvd', 'cd', 'disk', 'disc'],
		'📼': ['vhs', 'record', 'video', 'oldschool', '90s', 'cassette'],
		'📷': ['camera', 'gadgets', 'photography'],
		'📸': ['camera', 'photo', 'gadgets'],
		'📹': ['video', 'camera', 'film', 'record'],
		'🎥': ['movie', 'camera', 'film', 'record'],
		'📞': ['phone', 'call', 'telephone', 'dial', 'technology'],
		'☎️': ['phone', 'call', 'telephone', 'dial', 'technology'],
		'📟': ['pager', 'bbcall', 'oldschool', '90s'],
		'📠': ['fax', 'communication', 'technology'],
		'📺': ['tv', 'scan', 'television', 'program'],
		'📻': ['radio', 'communication', 'music', 'podcast', 'program'],
		'⏰': ['alarm', 'clock', 'time', 'wake'],
		'🕐': ['clock', 'time', 'late', 'early', 'schedule'],
		'⏳': ['hourglass', 'time', 'clock', 'oldschool', 'limit', 'exam', 'quiz', 'test'],
		'📡': ['satellite', 'communication', 'future', 'radio', 'space'],
		'🔋': ['battery', 'power', 'energy', 'sustain'],
		'🔌': ['electric', 'plug', 'charger', 'power'],
		'💡': ['light', 'electric', 'idea', 'smart', 'clever', 'bulb'],
		'🔦': ['flashlight', 'dark', 'camping', 'sight', 'night'],
		'🕯️': ['candle', 'fire', 'wax'],
		'🔧': ['wrench', 'tools', 'diy', 'ikea', 'fix', 'maintainer'],
		'🔨': ['hammer', 'tools', 'build', 'create', 'new', 'toy'],
		'⚒️': ['hammer', 'pick', 'tools', 'build', 'create'],
		'🛠️': ['hammer', 'wrench', 'tools', 'build', 'create'],
		'⛏️': ['pick', 'tools', 'dig'],
		'🔩': ['nut', 'bolt', 'handy', 'tools', 'fix'],
		'⚙️': ['gear', 'cog', 'wheel'],
		'🔪': ['knife', 'blade', 'cutlery', 'kitchen', 'weapon'],
		'🗡️': ['sword', 'weapon'],
		'⚔️': ['crossed', 'swords', 'weapon'],
		'🛡️': ['shield', 'protection', 'weapon'],
		'🚬': ['cigarette', 'kills', 'tobacco', 'cigarette', 'cancer'],
		'⚰️': ['coffin', 'vampire', 'dead', 'die', 'death', 'rip', 'graveyard', 'cemetery'],
		'⚱️': ['urn', 'dead', 'die', 'death', 'rip', 'ashes'],
		'🏺': ['amphora', 'vase', 'jar'],
		'🔮': ['crystal', 'ball', 'disco', 'party', 'magic', 'circus', 'fortune', 'teller'],
		'📿': ['prayer', 'beads', 'dhikr', 'religious'],
		'💈': ['barber', 'pole', 'hair', 'salon', 'style'],
		'⚗️': ['alembic', 'distilling', 'science', 'experiment', 'chemistry'],
		'🔭': ['telescope', 'stars', 'space', 'zoom', 'science', 'astronomy'],
		'🔬': ['microscope', 'laboratory', 'experiment', 'zoomin', 'science', 'study'],
		'🕳️': ['hole', 'embarrassing'],
		'💊': ['pill', 'health', 'medicine', 'doctor', 'pharmacy', 'drug'],
		'💉': ['syringe', 'health', 'hospital', 'drugs', 'blood', 'medicine', 'needle', 'doctor', 'nurse'],
		'🌡️': ['thermometer', 'weather', 'temperature', 'hot', 'cold'],
		'🚽': ['toilet', 'restroom', 'wc', 'washroom', 'bathroom', 'potty'],
		'🚰': ['potable', 'water', 'blue', 'liquid', 'faucet', 'clean', 'fresh', 'drink'],
		'🚿': ['shower', 'clean', 'water', 'bathroom'],
		'🛁': ['bathtub', 'clean', 'shower', 'bathroom'],
		'🛀': ['bath', 'clean', 'shower', 'bathroom'],
		'🧴': ['lotion', 'bottle', 'moisturizer', 'shampoo'],
		'🔑': ['key', 'lock', 'door', 'password'],
		'🗝️': ['key', 'lock', 'door', 'password'],
		'🚪': ['door', 'house', 'entry', 'exit'],
		'🛋️': ['couch', 'lamp', 'relax', 'sofa'],
		'🛏️': ['bed', 'sleep', 'rest'],
		'🛌': ['sleeping', 'bed', 'rest'],
		'🧸': ['teddy', 'bear', 'plush', 'stuffed'],
		'🖼️': ['framed', 'picture'],
		'🛍️': ['shopping', 'bags', 'mall', 'buy', 'purchase'],
		'🛒': ['shopping', 'trolley'],
		'🎁': ['gift', 'present', 'birthday', 'christmas', 'xmas'],
		'🎈': ['balloon', 'party', 'celebration', 'birthday'],
		'🎏': ['flags', 'fish', 'japanese', 'koinobori', 'carp', 'banner'],
		'🎀': ['ribbon', 'decoration', 'pink', 'girl', 'bowtie'],
		'🎊': ['confetti', 'ball', 'party', 'birthday'],
		'🎉': ['party', 'congratulations', 'birthday', 'magic', 'circus', 'celebration', 'tada'],
		'🧧': ['red', 'envelope', 'gift'],
		'❤️': ['love', 'like', 'heart'],
		'🧡': ['orange', 'heart', 'love'],
		'💛': ['yellow', 'heart', 'love'],
		'💚': ['green', 'heart', 'love'],
		'💙': ['blue', 'heart', 'love'],
		'💜': ['purple', 'heart', 'love'],
		'🖤': ['black', 'heart', 'evil'],
		'🤍': ['white', 'heart', 'pure'],
		'🤎': ['brown', 'heart', 'love'],
		'💔': ['broken', 'heart', 'sad', 'sorry', 'break', 'heartbreak'],
		'❣️': ['exclamation', 'heavy', 'heart', 'love', 'punctuation'],
		'💕': ['two', 'hearts', 'love', 'like', 'affection', 'valentines', 'heart'],
		'💞': ['revolving', 'hearts', 'love', 'like', 'affection', 'valentines'],
		'💓': ['beating', 'heart', 'love', 'like', 'affection', 'valentines', 'pink', 'heart'],
		'💗': ['growing', 'heart', 'like', 'love', 'affection', 'valentines', 'pink'],
		'💖': ['sparkling', 'heart', 'love', 'like', 'affection', 'valentines'],
		'💘': ['cupid', 'love', 'like', 'heart', 'affection', 'valentines'],
		'💝': ['gift', 'heart', 'love', 'valentines'],
		'💟': ['heart', 'decoration', 'purple', 'square', 'love', 'like'],
		'☮️': ['peace', 'symbol'],
		'✝️': ['cross', 'latin', 'christian'],
		'☪️': ['star', 'crescent', 'islam'],
		'🕉️': ['om', 'hinduism', 'buddhism', 'sikhism', 'jainism'],
		'☸️': ['wheel', 'dharma', 'hinduism', 'buddhism', 'sikhism', 'jainism'],
		'✡️': ['star', 'david', 'jewish'],
		'🔯': ['dotted', 'six', 'pointed', 'star'],
		'🕎': ['menorah', 'hanukkah', 'candles', 'jewish'],
		'☯️': ['yin', 'yang', 'balance'],
		'☦️': ['orthodox', 'cross', 'suppedaneum', 'religion'],
		'🛐': ['place', 'worship', 'religion', 'church', 'temple', 'prayer'],
		'⛎': ['ophiuchus', 'serpent', 'bearer', 'astrology'],
		'♈': ['aries', 'zodiac', 'astrology'],
		'♉': ['taurus', 'purple', 'zodiac', 'astrology'],
		'♊': ['gemini', 'zodiac', 'astrology'],
		'♋': ['cancer', 'zodiac', 'astrology'],
		'♌': ['leo', 'zodiac', 'astrology'],
		'♍': ['virgo', 'zodiac', 'astrology'],
		'♎': ['libra', 'zodiac', 'astrology'],
		'♏': ['scorpius', 'zodiac', 'astrology'],
		'♐': ['sagittarius', 'zodiac', 'astrology'],
		'♑': ['capricorn', 'zodiac', 'astrology'],
		'♒': ['aquarius', 'zodiac', 'astrology'],
		'♓': ['pisces', 'zodiac', 'astrology'],
		'🆔': ['squared', 'id'],
		'⚛️': ['atom', 'symbol', 'science', 'physics', 'chemistry'],
		'☢️': ['radioactive', 'nuclear', 'danger'],
		'☣️': ['biohazard', 'danger'],
		'📴': ['mobile', 'phone', 'off', 'mute', 'orange', 'square', 'silence', 'quiet'],
		'📳': ['vibration', 'mode', 'orange', 'square'],
		'❌': ['x', 'green', 'square', 'no', 'deny'],
		'⭕': ['o', 'red', 'circle', 'round'],
		'🛑': ['stop', 'halt', 'sign'],
		'⛔': ['no', 'entry', 'limit', 'security', 'privacy', 'bad', 'denied', 'stop', 'circle'],
		'📛': ['name', 'badge', 'fire', 'forbid'],
		'🚫': ['no', 'entry', 'sign', 'forbid', 'stop', 'limit', 'denied', 'disallow', 'circle'],
		'💯': ['hundred', 'score', 'perfect', 'numbers', 'century', 'exam', 'quiz', 'test', 'pass', 'hundred'],
		'💢': ['anger', 'angry', 'mad'],
		'♨️': ['hot', 'springs', 'steaming'],
		'🚷': ['no', 'pedestrians', 'rules', 'crossing', 'walking', 'circle'],
		'🚯': ['no', 'littering', 'trash', 'bin', 'garbage', 'circle'],
		'🚳': ['no', 'bicycles', 'cyclist', 'prohibited', 'circle'],
		'🚱': ['non', 'potable', 'water', 'drink', 'faucet', 'tap', 'circle'],
		'🔞': ['no', 'one', 'under', 'eighteen', '18', 'drink', 'pub', 'night', 'minor', 'circle'],
		'📵': ['no', 'mobile', 'phones', 'iphone', 'mute', 'circle'],
		'🚭': ['no', 'smoking', 'cigarette', 'blue', 'square', 'smell', 'smoke'],
		'❗': ['exclamation', 'heavy', 'mark', 'danger', 'surprise', 'punctuation', 'wow', 'warning'],
		'❕': ['exclamation', 'white', 'mark', 'surprise', 'punctuation', 'wow', 'warning'],
		'❓': ['question', 'mark', 'doubt', 'confused'],
		'❔': ['question', 'mark', 'doubts', 'gray', 'huh', 'confused'],
		'‼️': ['exclamation', 'bangbang', 'danger', 'surprise', 'punctuation', 'wow', 'warning'],
		'⁉️': ['interrobang', 'wat', 'punctuation', 'surprise'],
		'🔅': ['low', 'brightness', 'sun', 'afternoon', 'warm', 'summer'],
		'🔆': ['high', 'brightness', 'sun', 'light'],
		'〽️': ['part', 'alternation', 'mark', 'graph', 'presentation', 'stats', 'business', 'economics', 'bad'],
		'⚠️': ['warning', 'attention', 'exclamation', 'danger'],
		'🚸': ['children', 'crossing', 'school', 'warning', 'danger', 'sign', 'driving', 'yellow', 'diamond'],
		'🔱': ['trident', 'emblem', 'fork', 'weapon'],
		'⚜️': ['fleur', 'de', 'lis', 'decorative', 'scout'],
		'🔰': ['japanese', 'symbol', 'beginner', 'badge', 'shield'],
		'♻️': ['recycle', 'arrow', 'environment', 'garbage', 'trash'],
		'✅': ['white', 'heavy', 'check', 'mark', 'green', 'square', 'ok', 'agree', 'vote', 'election', 'answer', 'tick'],
		'💹': ['chart', 'graph', 'presentation', 'stats'],
		'❇️': ['sparkle', 'green', 'square', 'awesome', 'good', 'fireworks'],
		'✳️': ['eight', 'spoked', 'asterisk', 'green', 'square', 'sparkle'],
		'❎': ['cross', 'mark', 'green', 'square', 'no', 'deny'],
		'🌐': ['globe', 'world', 'international'],
		'💠': ['diamond', 'shape', 'jewel', 'blue'],
		'Ⓜ️': ['circled', 'latin', 'capital', 'letter', 'm', 'alphabet', 'blue', 'circle'],
		'🌀': ['cyclone', 'swirl'],
		'💤': ['zzz', 'sleepy', 'tired', 'dream'],
		'🏧': ['atm', 'sign', 'blue', 'square', 'payment', 'cash'],
		'🚾': ['water', 'closet', 'toilet', 'restroom', 'blue', 'square'],
		'♿': ['wheelchair', 'symbol', 'blue', 'square', 'disabled', 'a11y', 'accessibility'],
		'🅿️': ['parking', 'cars', 'blue', 'square', 'alphabet', 'letter'],
		'🈳': ['japanese', 'vacancy', 'kanji', 'japanese', 'chinese', 'empty', 'sky', 'blue', 'square'],
		'🈂️': ['japanese', 'service', 'charge', 'kanji', 'japanese', 'chinese', 'alphabet'],
		'🛂': ['passport', 'control', 'custom', 'blue', 'square'],
		'🛃': ['customs', 'passport', 'border', 'blue', 'square'],
		'🛄': ['baggage', 'claim', 'airport', 'transport', 'blue', 'square'],
		'🛅': ['left', 'luggage', 'blue', 'square', 'travel'],
		'🚹': ['mens', 'symbol', 'toilet', 'restroom', 'wc', 'blue', 'square'],
		'🚺': ['womens', 'symbol', 'purple', 'square'],
		'🚼': ['baby', 'symbol', 'orange', 'square', 'child'],
		'🚻': ['restroom', 'toilet', 'blue', 'square', 'person', 'gender', 'unknown'],
		'🚮': ['put', 'litter', 'in', 'its', 'place', 'blue', 'square', 'sign', 'human', 'info'],
		'🎦': ['cinema', 'blue', 'square', 'record', 'film', 'movie', 'curtain', 'stage', 'theater'],
		'📶': [
			'antenna',
			'bars',
			'blue',
			'square',
			'reception',
			'phone',
			'internet',
			'connection',
			'wifi',
			'bluetooth',
			'bars',
		],
		'🈁': ['japanese', 'here', 'katakana', 'japanese', 'chinese', 'red', 'square'],
		'🔣': ['symbols', 'blue', 'square', 'music', 'note', 'ampersand', 'percent', 'glyphs', 'characters'],
		ℹ️: ['information', 'source', 'alphabet', 'blue', 'square', 'letter'],
		'🔤': ['latin', 'small', 'letters', 'blue', 'square', 'alphabet'],
		'🔡': ['input', 'latin', 'lowercase', 'blue', 'square', 'alphabet'],
		'🔠': ['input', 'latin', 'uppercase', 'blue', 'square', 'alphabet'],
		'🆖': ['squared', 'ng', 'blue', 'square', 'words', 'shape'],
		'🆗': ['squared', 'ok', 'agree', 'yes', 'blue', 'square', 'like'],
		'🆙': ['squared', 'up', 'blue', 'square', 'above'],
		'🆒': ['squared', 'cool', 'words', 'blue', 'square'],
		'🆕': ['squared', 'new', 'blue', 'square', 'words', 'start'],
		'🆓': ['squared', 'free', 'blue', 'square', 'words'],
		'0️⃣': ['zero', 'numbers', 'blue', 'square', 'null'],
		'1️⃣': ['one', 'blue', 'square', 'numbers', '1'],
		'2️⃣': ['two', 'numbers', 'prime', 'blue', 'square'],
		'3️⃣': ['three', 'numbers', 'prime', 'blue', 'square'],
		'4️⃣': ['four', 'numbers', 'blue', 'square'],
		'5️⃣': ['five', 'numbers', 'blue', 'square', 'prime'],
		'6️⃣': ['six', 'numbers', 'blue', 'square'],
		'7️⃣': ['seven', 'numbers', 'blue', 'square', 'prime'],
		'8️⃣': ['eight', 'blue', 'square', 'numbers'],
		'9️⃣': ['nine', 'blue', 'square', 'numbers'],
		'🔟': ['ten', 'numbers', 'blue', 'square'],
		'🔢': ['input', 'numbers', '1234', 'blue', 'square'],
		'#️⃣': ['hash', 'number', 'blue', 'square', 'twitter'],
		'*️⃣': ['asterisk', 'star', 'keycap'],
		'⏏️': ['eject', 'blue', 'square'],
		'▶️': ['arrow', 'forward', 'blue', 'square', 'right', 'direction', 'play'],
		'⏸️': ['pause', 'blue', 'square'],
		'⏯️': ['play', 'pause', 'blue', 'square'],
		'⏹️': ['stop', 'blue', 'square'],
		'⏺️': ['record', 'blue', 'square'],
		'⏭️': ['next', 'track', 'forward', 'blue', 'square'],
		'⏮️': ['previous', 'track', 'backward', 'blue', 'square'],
		'⏩': ['fast', 'forward', 'blue', 'square', 'play', 'speed'],
		'⏪': ['rewind', 'play', 'blue', 'square'],
		'⏫': ['arrow', 'double', 'up', 'blue', 'square', 'direction'],
		'⏬': ['arrow', 'double', 'down', 'blue', 'square', 'direction'],
		'◀️': ['arrow', 'backward', 'blue', 'square', 'left', 'direction'],
		'🔼': ['arrow', 'small', 'up', 'blue', 'square', 'triangle', 'direction'],
		'🔽': ['arrow', 'small', 'down', 'blue', 'square', 'direction'],
		'➡️': ['arrow', 'right', 'blue', 'square', 'next'],
		'⬅️': ['arrow', 'left', 'blue', 'square', 'previous'],
		'⬆️': ['arrow', 'up', 'blue', 'square', 'continue'],
		'⬇️': ['arrow', 'down', 'blue', 'square'],
		'↗️': ['arrow', 'upper', 'right', 'blue', 'square', 'point', 'direction'],
		'↘️': ['arrow', 'lower', 'right', 'blue', 'square', 'direction'],
		'↙️': ['arrow', 'lower', 'left', 'blue', 'square', 'direction'],
		'↖️': ['arrow', 'upper', 'left', 'blue', 'square', 'point', 'direction'],
		'↕️': ['arrow', 'up', 'down', 'blue', 'square', 'direction'],
		'↔️': ['arrow', 'left', 'right', 'horizontal', 'blue', 'square'],
		'↪️': ['arrow', 'curving', 'left'],
		'↩️': ['leftwards', 'arrow', 'return', 'blue', 'square', 'undo', 'enter'],
		'⤴️': ['arrow', 'curving', 'up', 'blue', 'square'],
		'⤵️': ['arrow', 'curving', 'down', 'blue', 'square'],
		'🔀': ['twisted', 'rightwards', 'arrows', 'blue', 'square', 'shuffle', 'music', 'random'],
		'🔁': ['repeat', 'loop', 'record'],
		'🔂': ['repeat', 'single', 'music', 'loop'],
		'🔄': ['arrows', 'counterclockwise', 'blue', 'square', 'sync', 'cycle'],
		'🔃': ['arrows', 'clockwise', 'blue', 'square', 'sync', 'cycle', 'round', 'repeat'],
		'🎵': ['musical', 'note', 'score', 'tone', 'sound'],
		'🎶': ['musical', 'notes', 'music', 'score'],
		'➕': ['heavy', 'plus', 'sign', 'math', 'calculation', 'addition', 'more', 'increase'],
		'➖': ['heavy', 'minus', 'sign', 'math', 'calculation', 'subtract', 'less'],
		'➗': ['heavy', 'division', 'sign', 'math', 'calculation'],
		'✖️': ['heavy', 'multiplication', 'x', 'math', 'calculation'],
		'♾️': ['infinity', 'forever'],
		'💲': ['heavy', 'dollar', 'sign', 'money', 'sales', 'payment', 'currency'],
		'💱': ['currency', 'exchange', 'money', 'sales', 'dollar', 'travel'],
		'™️': ['trade', 'mark', 'sign', 'alphabet'],
		'©️': ['copyright', 'sign', 'alphabet'],
		'®️': ['registered', 'sign', 'alphabet'],
		'〰️': ['wavy', 'dash', 'draw', 'line', 'moustache', 'mustache', 'squiggle', 'scribble'],
		'➰': ['curly', 'loop'],
		'➿': ['double', 'curly', 'loop'],
		'🔚': ['end', 'words'],
		'🔙': ['back', 'arrow', 'words', 'return'],
		'🔛': ['on', 'arrow', 'words'],
		'🔝': ['top', 'words', 'blue', 'square'],
		'🔜': ['soon', 'arrow', 'words'],
		'✔️': ['heavy', 'check', 'mark', 'ok', 'nike', 'answer', 'yes', 'tick'],
		'☑️': ['white', 'heavy', 'check', 'mark', 'green', 'square', 'tick', 'yes', 'vote', 'election'],
		'🔘': ['radio', 'button', 'input', 'old', 'music'],
		'🔴': ['large', 'red', 'circle', 'shape'],
		'🟠': ['large', 'orange', 'circle'],
		'🟡': ['large', 'yellow', 'circle'],
		'🟢': ['large', 'green', 'circle'],
		'🔵': ['large', 'blue', 'circle', 'shape'],
		'🟣': ['large', 'purple', 'circle'],
		'⚫': ['medium', 'black', 'circle', 'shape', 'button', 'round'],
		'⚪': ['medium', 'white', 'circle', 'shape', 'round'],
		'🟤': ['large', 'brown', 'circle'],
		'🔺': ['small', 'red', 'triangle', 'shape', 'direction', 'up', 'top'],
		'🔻': ['small', 'red', 'triangle', 'down', 'shape', 'direction', 'bottom'],
		'🔸': ['small', 'orange', 'diamond', 'shape', 'jewel'],
		'🔹': ['small', 'blue', 'diamond', 'shape', 'jewel'],
		'🔶': ['large', 'orange', 'diamond', 'shape', 'jewel'],
		'🔷': ['large', 'blue', 'diamond', 'shape', 'jewel'],
		'🔳': ['white', 'large', 'square', 'shape', 'icon', 'button'],
		'🔲': ['black', 'large', 'square', 'shape', 'icon', 'button'],
		'▪️': ['black', 'small', 'square', 'shape', 'icon'],
		'▫️': ['white', 'small', 'square', 'shape', 'icon'],
		'◾': ['black', 'medium', 'small', 'square', 'shape', 'button', 'icon'],
		'◽': ['white', 'medium', 'small', 'square', 'shape', 'stone', 'icon'],
		'◼️': ['black', 'medium', 'square', 'shape', 'button', 'icon'],
		'◻️': ['white', 'medium', 'square', 'shape', 'stone', 'icon'],
		'🟥': ['large', 'red', 'square'],
		'🟧': ['large', 'orange', 'square'],
		'🟨': ['large', 'yellow', 'square'],
		'🟩': ['large', 'green', 'square'],
		'🟦': ['large', 'blue', 'square'],
		'🟪': ['large', 'purple', 'square'],
		'⬛': ['large', 'black', 'square', 'shape', 'icon'],
		'⬜': ['large', 'white', 'square', 'shape', 'icon', 'stone', 'button'],
		'🟫': ['large', 'brown', 'square'],
		'🔈': ['speaker', 'low', 'volume', 'sound', 'quiet'],
		'🔇': ['muted', 'speaker', 'sound', 'volume', 'silence', 'quiet'],
		'🔉': ['speaker', 'medium', 'volume', 'sound'],
		'🔊': ['speaker', 'high', 'volume', 'sound', 'loud'],
		'🔔': ['bell', 'sound', 'notification', 'christmas', 'xmas', 'chime'],
		'🔕': ['bell', 'with', 'cancellation', 'stroke', 'mute', 'sound', 'volume'],
		'📣': ['cheering', 'megaphone', 'sound', 'speaker', 'volume'],
		'📢': ['loudspeaker', 'volume', 'sound'],
		'💬': ['speech', 'balloon', 'bubble', 'words', 'message', 'talk', 'chatting'],
		'💭': ['thought', 'balloon', 'bubble', 'cloud', 'speech', 'thinking', 'dream'],
		'🗯️': ['right', 'anger', 'bubble', 'balloon', 'mad'],
		'♠️': ['spade', 'suit', 'poker', 'cards', 'suits', 'magic'],
		'♣️': ['club', 'suit', 'poker', 'cards', 'magic', 'suits'],
		'♥️': ['heart', 'suit', 'poker', 'cards', 'magic', 'suits'],
		'♦️': ['diamond', 'suit', 'poker', 'cards', 'magic', 'suits'],
		'🃏': ['joker', 'poker', 'cards', 'game', 'play', 'magic'],
		'🎴': ['flower', 'playing', 'cards', 'japanese', 'deck'],
		'🀄': ['mahjong', 'game', 'play', 'chinese', 'kanji'],
	};

	const emojiCategories = {
		smileys: {
			name: '😀',
			title: 'Smileys & Emotion',
			emojis: [
				'😀',
				'😃',
				'😄',
				'😁',
				'😅',
				'😂',
				'🤣',
				'😊',
				'😇',
				'🙂',
				'😉',
				'😌',
				'😍',
				'🥰',
				'😘',
				'😋',
				'😛',
				'😜',
				'🤪',
				'😝',
				'🤔',
				'😐',
				'😑',
				'😶',
				'😏',
				'😒',
				'🙄',
				'😬',
				'😔',
				'😪',
				'😴',
				'😷',
				'🤒',
				'🤕',
				'🤢',
				'🤮',
				'🤧',
				'😵',
				'🤯',
				'😎',
				'🤓',
				'😕',
				'😟',
				'🙁',
				'☹️',
				'😮',
				'😯',
				'😲',
				'😳',
				'😦',
				'😧',
				'😨',
				'😰',
				'😥',
				'😢',
				'😭',
				'😱',
				'😖',
				'😣',
				'😞',
				'😓',
				'😩',
				'😫',
				'😤',
				'😡',
				'😠',
				'😈',
				'👿',
				'💀',
				'☠️',
				'💩',
				'🤡',
				'👹',
				'👺',
				'👻',
				'👽',
				'👾',
				'🤖',
			],
		},
		gestures: {
			name: '👋',
			title: 'People & Body',
			emojis: [
				'👋',
				'🤚',
				'🖐️',
				'✋',
				'🖖',
				'👌',
				'🤏',
				'✌️',
				'🤞',
				'🤟',
				'🤘',
				'🤙',
				'👈',
				'👉',
				'👆',
				'🖕',
				'👇',
				'☝️',
				'👍',
				'👎',
				'✊',
				'👊',
				'🤛',
				'🤜',
				'👏',
				'🙌',
				'👐',
				'🤲',
				'🤝',
				'🙏',
				'✍️',
				'💅',
				'🤳',
				'💪',
				'🦾',
				'🦿',
				'🦵',
				'🦶',
				'👂',
				'🦻',
				'👃',
				'🧠',
				'🦷',
				'🦴',
				'👀',
				'👁️',
				'👅',
				'👄',
				'💋',
			],
		},
		nature: {
			name: '🐶',
			title: 'Animals & Nature',
			emojis: [
				'🐶',
				'🐱',
				'🐭',
				'🐹',
				'🐰',
				'🦊',
				'🐻',
				'🐼',
				'🐨',
				'🐯',
				'🦁',
				'🐮',
				'🐷',
				'🐽',
				'🐸',
				'🐵',
				'🙈',
				'🙉',
				'🙊',
				'🐒',
				'🐔',
				'🐧',
				'🐦',
				'🐤',
				'🐣',
				'🐥',
				'🦆',
				'🦅',
				'🦉',
				'🦇',
				'🐺',
				'🐗',
				'🐴',
				'🦄',
				'🐝',
				'🐛',
				'🦋',
				'🐌',
				'🐞',
				'🐜',
				'🦟',
				'🦗',
				'🕷️',
				'🕸️',
				'🦂',
				'🐢',
				'🐍',
				'🦎',
				'🦖',
				'🦕',
				'🐙',
				'🦑',
				'🦐',
				'🦞',
				'🦀',
				'🐡',
				'🐠',
				'🐟',
				'🐬',
				'🐳',
				'🐋',
				'🦈',
				'🐊',
				'🐅',
				'🐆',
				'🦓',
				'🦍',
				'🦧',
				'🐘',
				'🦛',
				'🦏',
				'🐪',
				'🐫',
				'🦒',
				'🦘',
				'🐃',
				'🐂',
				'🐄',
				'🐎',
				'🐖',
				'🐏',
				'🐑',
				'🦙',
				'🐐',
				'🦌',
				'🐕',
				'🐩',
				'🦮',
				'🐕‍🦺',
				'🐈',
				'🐈‍⬛',
				'🐓',
				'🦃',
				'🦚',
				'🦜',
				'🦢',
				'🦩',
				'🕊️',
				'🐇',
				'🦝',
				'🦨',
				'🦡',
				'🦫',
				'🦦',
				'🦥',
				'🐁',
				'🐀',
				'🐿️',
				'🦔',
				'🌵',
				'🎄',
				'🌲',
				'🌳',
				'🌴',
				'🌱',
				'🌿',
				'☘️',
				'🍀',
				'🎍',
				'🎋',
				'🍃',
				'🍂',
				'🍁',
				'🍄',
				'🐚',
				'🌾',
				'💐',
				'🌷',
				'🌹',
				'🥀',
				'🌺',
				'🌸',
				'🌼',
				'🌻',
				'🌞',
				'🌝',
				'🌛',
				'🌜',
				'🌚',
				'🌕',
				'🌖',
				'🌗',
				'🌘',
				'🌑',
				'🌒',
				'🌓',
				'🌔',
				'🌙',
				'🌎',
				'🌍',
				'🌏',
				'💫',
				'⭐',
				'🌟',
				'✨',
				'⚡',
				'☄️',
				'💥',
				'🔥',
				'🌪️',
				'🌈',
				'☀️',
				'🌤️',
				'⛅',
				'🌥️',
				'☁️',
				'🌦️',
				'🌧️',
				'⛈️',
				'🌩️',
				'🌨️',
				'❄️',
				'☃️',
				'⛄',
				'🌬️',
				'💨',
				'💧',
				'💦',
				'☔',
				'☂️',
				'🌊',
				'🌫️',
			],
		},
		food: {
			name: '🍎',
			title: 'Food & Drink',
			emojis: [
				'🍏',
				'🍎',
				'🍐',
				'🍊',
				'🍋',
				'🍌',
				'🍉',
				'🍇',
				'🍓',
				'🫐',
				'🍈',
				'🍒',
				'🍑',
				'🥭',
				'🍍',
				'🥥',
				'🥝',
				'🍅',
				'🍆',
				'🥑',
				'🥦',
				'🥬',
				'🥒',
				'🌶️',
				'🫑',
				'🌽',
				'🥕',
				'🫒',
				'🧄',
				'🧅',
				'🥔',
				'🍠',
				'🥐',
				'🥯',
				'🍞',
				'🥖',
				'🥨',
				'🧀',
				'🥚',
				'🍳',
				'🧈',
				'🥞',
				'🧇',
				'🥓',
				'🥩',
				'🍗',
				'🍖',
				'🌭',
				'🍔',
				'🍟',
				'🍕',
				'🥪',
				'🥙',
				'🧆',
				'🌮',
				'🌯',
				'🫔',
				'🥗',
				'🥘',
				'🫕',
				'🥫',
				'🍝',
				'🍜',
				'🍲',
				'🍛',
				'🍣',
				'🍱',
				'🥟',
				'🦪',
				'🍤',
				'🍙',
				'🍚',
				'🍘',
				'🍥',
				'🥠',
				'🥮',
				'🍢',
				'🍡',
				'🍧',
				'🍨',
				'🍦',
				'🥧',
				'🧁',
				'🍰',
				'🎂',
				'🍮',
				'🍭',
				'🍬',
				'🍫',
				'🍿',
				'🍩',
				'🍪',
				'🌰',
				'🥜',
				'🍯',
				'🥛',
				'🍼',
				'☕',
				'🍵',
				'🧃',
				'🥤',
				'🧋',
				'🍶',
				'🍺',
				'🍻',
				'🥂',
				'🍷',
				'🥃',
				'🍸',
				'🍹',
				'🧉',
				'🍾',
				'🧊',
			],
		},
		objects: {
			name: '⚽',
			title: 'Activities & Objects',
			emojis: [
				'⚽',
				'🏀',
				'🏈',
				'⚾',
				'🥎',
				'🎾',
				'🏐',
				'🏉',
				'🥏',
				'🎱',
				'🪀',
				'🏓',
				'🏸',
				'🏒',
				'🏑',
				'🥍',
				'🏏',
				'🪃',
				'🥅',
				'⛳',
				'🪁',
				'🏹',
				'🎣',
				'🤿',
				'🥊',
				'🥋',
				'🎽',
				'🛹',
				'🛼',
				'🛷',
				'⛸️',
				'🥌',
				'🎿',
				'⛷️',
				'🏂',
				'🪂',
				'🏋️',
				'🤼',
				'🤸',
				'⛹️',
				'🤺',
				'🤾',
				'🏌️',
				'🏇',
				'🧘',
				'🏄',
				'🏊',
				'🤽',
				'🚣',
				'🧗',
				'🚵',
				'🚴',
				'🏆',
				'🥇',
				'🥈',
				'🥉',
				'🏅',
				'🎖️',
				'🏵️',
				'🎗️',
				'🎫',
				'🎟️',
				'🎪',
				'🤹',
				'🎭',
				'🩰',
				'🎨',
				'🎬',
				'🎤',
				'🎧',
				'🎼',
				'🎹',
				'🥁',
				'🪘',
				'🎷',
				'🎺',
				'🪗',
				'🎸',
				'🪕',
				'🎻',
				'🎲',
				'♟️',
				'🎯',
				'🎳',
				'🎮',
				'🎰',
				'🧩',
				'🚗',
				'🚕',
				'🚙',
				'🚌',
				'🚎',
				'🏎️',
				'🚓',
				'🚑',
				'🚒',
				'🚐',
				'🛻',
				'🚚',
				'🚛',
				'🚜',
				'🦯',
				'🦽',
				'🦼',
				'🛴',
				'🚲',
				'🛵',
				'🏍️',
				'🛺',
				'🚨',
				'🚔',
				'🚍',
				'🚘',
				'🚖',
				'🚡',
				'🚠',
				'🚟',
				'🚃',
				'🚋',
				'🚞',
				'🚝',
				'🚄',
				'🚅',
				'🚈',
				'🚂',
				'🚆',
				'🚇',
				'🚊',
				'🚉',
				'✈️',
				'🛫',
				'🛬',
				'🛩️',
				'💺',
				'🛰️',
				'🚀',
				'🛸',
				'🚁',
				'🛶',
				'⛵',
				'🚤',
				'🛥️',
				'🛳️',
				'⛴️',
				'🚢',
				'⚓',
				'⛽',
				'🚧',
				'🚦',
				'🚥',
				'🚏',
				'🗺️',
				'🗿',
				'🗽',
				'🗼',
				'🏰',
				'🏯',
				'🏟️',
				'🎡',
				'🎢',
				'🎠',
				'⛲',
				'⛱️',
				'🏖️',
				'🏝️',
				'🏜️',
				'🌋',
				'⛰️',
				'🏔️',
				'🗻',
				'🏕️',
				'⛺',
				'🏠',
				'🏡',
				'🏘️',
				'🏚️',
				'🏗️',
				'🏭',
				'🏢',
				'🏬',
				'🏣',
				'🏤',
				'🏥',
				'🏦',
				'🏨',
				'🏪',
				'🏫',
				'🏩',
				'💒',
				'🏛️',
				'⛪',
				'🕌',
				'🛕',
				'🕍',
				'⛩️',
				'🏙️',
				'🌃',
				'🏞️',
				'🌉',
				'🌁',
				'⌚',
				'📱',
				'📲',
				'💻',
				'⌨️',
				'🖥️',
				'🖨️',
				'🖱️',
				'🖲️',
				'🕹️',
				'🗜️',
				'💽',
				'💾',
				'💿',
				'📀',
				'📼',
				'📷',
				'📸',
				'📹',
				'🎥',
				'📽️',
				'🎞️',
				'📞',
				'☎️',
				'📟',
				'📠',
				'📺',
				'📻',
				'🎙️',
				'🎚️',
				'🎛️',
				'🧭',
				'⏱️',
				'⏲️',
				'⏰',
				'🕰️',
				'⌛',
				'⏳',
				'📡',
				'🔋',
				'🔌',
				'💡',
				'🔦',
				'🕯️',
				'🪔',
				'🧯',
				'🛢️',
				'💸',
				'💵',
				'💴',
				'💶',
				'💷',
				'🪙',
				'💰',
				'💳',
				'💎',
				'⚖️',
				'🪜',
				'🧰',
				'🪛',
				'🔧',
				'🔨',
				'⚒️',
				'🛠️',
				'⛏️',
				'🪚',
				'🔩',
				'⚙️',
				'🪤',
				'🧱',
				'⛓️',
				'🧲',
				'🔫',
				'💣',
				'🧨',
				'🪓',
				'🔪',
				'🗡️',
				'⚔️',
				'🛡️',
				'🚬',
				'⚰️',
				'🪦',
				'⚱️',
				'🏺',
				'🔮',
				'📿',
				'🧿',
				'💈',
				'⚗️',
				'🔭',
				'🔬',
				'🕳️',
				'🩹',
				'🩺',
				'💊',
				'💉',
				'🩸',
				'🧬',
				'🦠',
				'🧫',
				'🧪',
				'🌡️',
				'🧹',
				'🪠',
				'🧺',
				'🧻',
				'🚽',
				'🚰',
				'🚿',
				'🛁',
				'🛀',
				'🧼',
				'🪥',
				'🪒',
				'🧽',
				'🪣',
				'🧴',
				'🛎️',
				'🔑',
				'🗝️',
				'🚪',
				'🪑',
				'🛋️',
				'🛏️',
				'🛌',
				'🧸',
				'🪆',
				'🖼️',
				'🪞',
				'🪟',
				'🛍️',
				'🛒',
				'🎁',
				'🎈',
				'🎏',
				'🎀',
				'🪄',
				'🪅',
				'🎊',
				'🎉',
				'🎎',
				'🏮',
				'🎐',
				'🧧',
			],
		},
		symbols: {
			name: '❤️',
			title: 'Symbols',
			emojis: [
				'❤️',
				'🧡',
				'💛',
				'💚',
				'💙',
				'💜',
				'🖤',
				'🤍',
				'🤎',
				'💔',
				'❣️',
				'💕',
				'💞',
				'💓',
				'💗',
				'💖',
				'💘',
				'💝',
				'💟',
				'☮️',
				'✝️',
				'☪️',
				'🕉️',
				'☸️',
				'✡️',
				'🔯',
				'🕎',
				'☯️',
				'☦️',
				'🛐',
				'⛎',
				'♈',
				'♉',
				'♊',
				'♋',
				'♌',
				'♍',
				'♎',
				'♏',
				'♐',
				'♑',
				'♒',
				'♓',
				'🆔',
				'⚛️',
				'🉑',
				'☢️',
				'☣️',
				'📴',
				'📳',
				'🈶',
				'🈚',
				'🈸',
				'🈺',
				'🈷️',
				'✴️',
				'🆚',
				'💮',
				'🉐',
				'㊙️',
				'㊗️',
				'🈴',
				'🈵',
				'🈹',
				'🈲',
				'🅰️',
				'🅱️',
				'🆎',
				'🆑',
				'🅾️',
				'🆘',
				'❌',
				'⭕',
				'🛑',
				'⛔',
				'📛',
				'🚫',
				'💯',
				'💢',
				'♨️',
				'🚷',
				'🚯',
				'🚳',
				'🚱',
				'🔞',
				'📵',
				'🚭',
				'❗',
				'❕',
				'❓',
				'❔',
				'‼️',
				'⁉️',
				'🔅',
				'🔆',
				'〽️',
				'⚠️',
				'🚸',
				'🔱',
				'⚜️',
				'🔰',
				'♻️',
				'✅',
				'🈯',
				'💹',
				'❇️',
				'✳️',
				'❎',
				'🌐',
				'💠',
				'Ⓜ️',
				'🌀',
				'💤',
				'🏧',
				'🚾',
				'♿',
				'🅿️',
				'🛗',
				'🈳',
				'🈂️',
				'🛂',
				'🛃',
				'🛄',
				'🛅',
				'🚹',
				'🚺',
				'🚼',
				'⚧️',
				'🚻',
				'🚮',
				'🎦',
				'📶',
				'🈁',
				'🔣',
				'ℹ️',
				'🔤',
				'🔡',
				'🔠',
				'🆖',
				'🆗',
				'🆙',
				'🆒',
				'🆕',
				'🆓',
				'0️⃣',
				'1️⃣',
				'2️⃣',
				'3️⃣',
				'4️⃣',
				'5️⃣',
				'6️⃣',
				'7️⃣',
				'8️⃣',
				'9️⃣',
				'🔟',
				'🔢',
				'#️⃣',
				'*️⃣',
				'⏏️',
				'▶️',
				'⏸️',
				'⏯️',
				'⏹️',
				'⏺️',
				'⏭️',
				'⏮️',
				'⏩',
				'⏪',
				'⏫',
				'⏬',
				'◀️',
				'🔼',
				'🔽',
				'➡️',
				'⬅️',
				'⬆️',
				'⬇️',
				'↗️',
				'↘️',
				'↙️',
				'↖️',
				'↕️',
				'↔️',
				'↪️',
				'↩️',
				'⤴️',
				'⤵️',
				'🔀',
				'🔁',
				'🔂',
				'🔄',
				'🔃',
				'🎵',
				'🎶',
				'➕',
				'➖',
				'➗',
				'✖️',
				'♾️',
				'💲',
				'💱',
				'™️',
				'©️',
				'®️',
				'〰️',
				'➰',
				'➿',
				'🔚',
				'🔙',
				'🔛',
				'🔝',
				'🔜',
				'✔️',
				'☑️',
				'🔘',
				'🔴',
				'🟠',
				'🟡',
				'🟢',
				'🔵',
				'🟣',
				'⚫',
				'⚪',
				'🟤',
				'🔺',
				'🔻',
				'🔸',
				'🔹',
				'🔶',
				'🔷',
				'🔳',
				'🔲',
				'▪️',
				'▫️',
				'◾',
				'◽',
				'◼️',
				'◻️',
				'🟥',
				'🟧',
				'🟨',
				'🟩',
				'🟦',
				'🟪',
				'⬛',
				'⬜',
				'🟫',
				'🔈',
				'🔇',
				'🔉',
				'🔊',
				'🔔',
				'🔕',
				'📣',
				'📢',
				'👁‍🗨',
				'💬',
				'💭',
				'🗯️',
				'♠️',
				'♣️',
				'♥️',
				'♦️',
				'🃏',
				'🎴',
				'🀄',
			],
		},
	};

	const getFilteredEmojis = () => {
		if (!emojiSearch) {
			return emojiCategories[selectedCategory as keyof typeof emojiCategories]?.emojis || [];
		}

		const searchTerm = emojiSearch.toLowerCase();
		const filteredEmojis: string[] = [];

		Object.entries(emojiMap).forEach(([emoji, keywords]) => {
			if (keywords.some((keyword) => keyword.toLowerCase().includes(searchTerm))) {
				filteredEmojis.push(emoji);
			}
		});

		return filteredEmojis;
	};

	return (
		<S.Emojis>
			<S.EmojisIcon ref={emojiButtonRef} onClick={() => setIsVisible(!isVisible)}>
				<ReactSVG src={ICONS.emoji} />
			</S.EmojisIcon>
			{isVisible && (
				<S.EmojiPicker ref={emojiPickerRef}>
					<S.EmojiSearch>
						<S.EmojiSearchInput
							type="text"
							placeholder="Search emojis..."
							value={emojiSearch}
							onChange={(e) => setEmojiSearch(e.target.value)}
							autoFocus
						/>
					</S.EmojiSearch>
					{!emojiSearch && (
						<S.EmojiCategories>
							{Object.entries(emojiCategories).map(([key, category]) => (
								<S.EmojiCategoryTab
									key={key}
									$active={selectedCategory === key}
									onClick={() => setSelectedCategory(key)}
									title={category.title}
								>
									{category.name}
								</S.EmojiCategoryTab>
							))}
						</S.EmojiCategories>
					)}
					<S.EmojiGrid>
						{getFilteredEmojis().map((emoji, index) => (
							<S.EmojiButton key={`${emoji}-${index}`} onClick={() => handleEmoji(emoji)} title={emoji}>
								{emoji}
							</S.EmojiButton>
						))}
					</S.EmojiGrid>
				</S.EmojiPicker>
			)}
		</S.Emojis>
	);
}
