name: publish

on:
  push:
    branches: ['main', 'staging']

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm run clean:install
      - run: npm run deploy:editor:main
      - run: npm run deploy:viewer

  publish-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm run clean:install
      - run: npm run deploy:editor:staging
      - run: npm run deploy:viewer
