name: Deploy Editor

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Target'
        required: true
        default: 'main'
        type: choice
        options:
          - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm run clean:install
      - name: Deploy editor to (staging_portalenv.arweave.net)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run deploy:editor:staging
      - name: Deploy editor to (portal.arweave.net)
        if: github.event_name == 'workflow_dispatch'
        run: npm run deploy:editor:main
